2016-11-03 22:26:02,966 | INFO     | log.py               (128) | setupLogging | Choosing RAET log level 4
2016-11-03 22:26:06,084 | DEBUG    | testable.py          (126) | decorator | in SpyableTestClient added spy on __init__
2016-11-03 22:26:06,085 | WARNING  | testable.py          (134) | decorator | method <function Client.handleOneNodeMsg at 0x7f280bc19ea0> not found, so no spy added
2016-11-03 22:26:06,099 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on __init__
2016-11-03 22:26:06,103 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterReqLatencyTooHigh
2016-11-03 22:26:06,103 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterThroughputTooLow
2016-11-03 22:26:06,103 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on sendThroughput
2016-11-03 22:26:06,106 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on __init__
2016-11-03 22:26:06,106 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on catchupCompleted
2016-11-03 22:26:06,106 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on processConsistencyProofReq
2016-11-03 22:26:06,106 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on startCatchUpProcess
2016-11-03 22:26:06,115 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on __init__
2016-11-03 22:26:06,115 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on addToPrePrepares
2016-11-03 22:26:06,115 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canProcessPrePrepare
2016-11-03 22:26:06,115 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canSendPrepare
2016-11-03 22:26:06,116 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doOrder
2016-11-03 22:26:06,116 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrePrepare
2016-11-03 22:26:06,116 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrepare
2016-11-03 22:26:06,116 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on isValidPrepare
2016-11-03 22:26:06,116 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on orderPendingCommit
2016-11-03 22:26:06,116 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processCommit
2016-11-03 22:26:06,116 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrePrepare
2016-11-03 22:26:06,116 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrepare
2016-11-03 22:26:06,124 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on __init__
2016-11-03 22:26:06,124 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on checkPerformance
2016-11-03 22:26:06,124 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on decidePrimaries
2016-11-03 22:26:06,124 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on discard
2016-11-03 22:26:06,125 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on eatTestMsg
2016-11-03 22:26:06,125 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on forward
2016-11-03 22:26:06,125 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleInvalidClientMsg
2016-11-03 22:26:06,125 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleOneNodeMsg
2016-11-03 22:26:06,125 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToClientInBox
2016-11-03 22:26:06,125 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToNodeInBox
2016-11-03 22:26:06,125 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processInstanceChange
2016-11-03 22:26:06,125 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processOrdered
2016-11-03 22:26:06,125 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processPropagate
2016-11-03 22:26:06,125 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processRequest
2016-11-03 22:26:06,126 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on propagate
2016-11-03 22:26:06,126 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousClient
2016-11-03 22:26:06,126 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousNode
2016-11-03 22:26:06,126 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on send
2016-11-03 22:26:06,126 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on sendInstanceChange
2016-11-03 22:26:06,126 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on startViewChange
Loading module /home/lovesh/.virtualenvs/sovrin-dev/lib/python3.5/site-packages/anoncreds_dev-0.1.8-py3.5.egg/config/config-crypto-example1.py
Module loaded.
2016-11-03 22:26:06,751 | DEBUG    | gen_load_ratcheting  (280) | main | Results file: /home/lovesh/dev/evernym/sovrin-priv/scripts/perf_results_1_2_1478192166.csv
2016-11-03 22:26:06,769 | INFO     | gen_load_ratcheting  (136) | _spawnClient | Seed for client Client7 is b'0000000000000000000000000Client7', its len is 32
2016-11-03 22:26:06,770 | DEBUG    | client.py            (76) | __init__ | Client Client7 ignoring given ha HA(host='0.0.0.0', port=6360) and using HA(host='127.0.0.1', port=6580)
2016-11-03 22:26:06,770 | DEBUG    | ledger.py            (164) | start | Starting ledger...
2016-11-03 22:26:06,770 | DEBUG    | ledger.py            (69) | recoverTree | Recovering tree from transaction log
Stack 'Client7': Opened server at '('0.0.0.0', 6580)'
2016-11-03 22:26:06,848 | INFO     | client.py            (121) | __init__ | Client Client7 initialized with the following node registry:
2016-11-03 22:26:06,848 | INFO     | client.py            (128) | __init__ |     Node1C listens at 35.161.137.38  on port 9702
2016-11-03 22:26:06,848 | INFO     | client.py            (128) | __init__ |     Node2C listens at 35.161.111.17  on port 9704
2016-11-03 22:26:06,848 | INFO     | client.py            (128) | __init__ |     Node3C listens at 35.161.122.249 on port 9706
2016-11-03 22:26:06,848 | INFO     | client.py            (128) | __init__ |     Node4C listens at 35.160.153.163 on port 9708
2016-11-03 22:26:06,848 | INFO     | client.py            (128) | __init__ |     Node5C listens at 54.147.219.106 on port 9710
2016-11-03 22:26:06,848 | INFO     | client.py            (128) | __init__ |     Node6C listens at 52.199.48.127  on port 9712
2016-11-03 22:26:06,848 | INFO     | client.py            (128) | __init__ |     Node7C listens at 54.169.186.146 on port 9714
2016-11-03 22:26:06,848 | DEBUG    | plugin_helper.py     (25) | loadPlugins | Plugin loading started to load plugins from basedir: /home/lovesh/.sovrin
2016-11-03 22:26:07,447 | DEBUG    | plugin_helper.py     (68) | loadPlugins | Total plugins loaded from basedir /home/lovesh/.sovrin are : 1
2016-11-03 22:26:07,447 | DEBUG    | client.py            (148) | __init__ | total plugins loaded in client: 1
2016-11-03 22:26:07,448 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
2016-11-03 22:26:07,448 | DEBUG    | looper.py            (121) | __init__ | Setting handler for SIGINT
2016-11-03 22:26:07,448 | DEBUG    | motor.py             (34) | set_status | Client7 changing status from stopped to starting
2016-11-03 22:26:07,448 | INFO     | stacked.py           (75) | start | stack Client7 starting at ('0.0.0.0', 6580) in always mode
2016-11-03 22:26:07,448 | INFO     | stacked.py           (851) | start | Client7 listening for other nodes at 0.0.0.0:6580
2016-11-03 22:26:07,449 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client7 retrying to connect with Node4C
Added transaction to Node4C at '(False, 6, 11, 35, 1, False)'
Allower Client7. Do Hello with Node4C in 1 at 0.6009826679946855
2016-11-03 22:26:07,454 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client7 disconnected node is joined
2016-11-03 22:26:07,454 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client7 retrying to connect with Node3C
Added transaction to Node3C at '(False, 4, 11, 35, 1, False)'
Allower Client7. Do Hello with Node3C in 1 at 0.6063961729960283
2016-11-03 22:26:07,457 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client7 disconnected node is joined
2016-11-03 22:26:07,457 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client7 retrying to connect with Node7C
Added transaction to Node7C at '(False, 7, 11, 35, 1, False)'
Allower Client7. Do Hello with Node7C in 1 at 0.6099256459929165
2016-11-03 22:26:07,463 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client7 disconnected node is joined
2016-11-03 22:26:07,463 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client7 retrying to connect with Node6C
Added transaction to Node6C at '(False, 2, 11, 35, 1, False)'
Allower Client7. Do Hello with Node6C in 1 at 0.615520037994429
2016-11-03 22:26:07,469 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client7 disconnected node is joined
2016-11-03 22:26:07,469 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client7 retrying to connect with Node5C
Added transaction to Node5C at '(False, 3, 11, 35, 1, False)'
Allower Client7. Do Hello with Node5C in 1 at 0.6211574049957562
2016-11-03 22:26:07,474 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client7 disconnected node is joined
2016-11-03 22:26:07,474 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client7 retrying to connect with Node2C
Added transaction to Node2C at '(False, 5, 11, 35, 1, False)'
Allower Client7. Do Hello with Node2C in 1 at 0.6267201509981533
2016-11-03 22:26:07,480 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client7 disconnected node is joined
2016-11-03 22:26:07,480 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client7 retrying to connect with Node1C
Added transaction to Node1C at '(False, 8, 11, 35, 1, False)'
Allower Client7. Do Hello with Node1C in 1 at 0.6323172669945052
2016-11-03 22:26:07,485 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client7 disconnected node is joined
2016-11-03 22:26:07,485 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Client7 nodereg is odict_items([('Node1C', HA(host='35.161.137.38', port=9702)), ('Node2C', HA(host='35.161.111.17', port=9704)), ('Node3C', HA(host='35.161.122.249', port=9706)), ('Node4C', HA(host='35.160.153.163', port=9708)), ('Node5C', HA(host='54.147.219.106', port=9710)), ('Node6C', HA(host='52.199.48.127', port=9712)), ('Node7C', HA(host='54.169.186.146', port=9714))])
2016-11-03 22:26:07,485 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Client7 nodestack is ['Node4C', 'Node3C', 'Node7C', 'Node6C', 'Node5C', 'Node2C', 'Node1C']
2016-11-03 22:26:07,486 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 6 ('35.160.153.163', 9708)
2016-11-03 22:26:07,486 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 4 ('35.161.122.249', 9706)
2016-11-03 22:26:07,486 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 7 ('54.169.186.146', 9714)
2016-11-03 22:26:07,486 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 2 ('52.199.48.127', 9712)
2016-11-03 22:26:07,486 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 3 ('54.147.219.106', 9710)
2016-11-03 22:26:07,486 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 5 ('35.161.111.17', 9704)
2016-11-03 22:26:07,486 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 8 ('35.161.137.38', 9702)
2016-11-03 22:26:07,486 | DEBUG    | stacked.py           (490) | maintainConnections | Client7 next check for retries in 6.00 seconds
2016-11-03 22:26:07,488 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:07,864 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:08,240 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Allower Client7. Redo Hello with Node4C in 1 at 1.6018549309956143
Allower Client7. Redo Hello with Node3C in 1 at 1.6154083929941407
Allower Client7. Redo Hello with Node7C in 1 at 1.6154083929941407
Allower Client7. Redo Hello with Node6C in 1 at 1.6302536479997798
Allower Client7. Redo Hello with Node5C in 1 at 1.6302536479997798
Allower Client7. Redo Hello with Node2C in 1 at 1.6302536479997798
Allower Client7. Redo Hello with Node1C in 1 at 1.6474413899995852
2016-11-03 22:26:08,618 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:08,995 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:09,371 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:09,747 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:10,124 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Allower Client7. Redo Hello with Node4C in 1 at 3.616122045998054
Allower Client7. Redo Hello with Node3C in 1 at 3.616122045998054
Allower Client7. Redo Hello with Node7C in 1 at 3.616122045998054
Allower Client7. Redo Hello with Node6C in 1 at 3.6449657139964984
Allower Client7. Redo Hello with Node5C in 1 at 3.6449657139964984
Allower Client7. Redo Hello with Node2C in 1 at 3.6449657139964984
2016-11-03 22:26:10,500 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Allower Client7. Redo Hello with Node1C in 1 at 3.6639018719943124
2016-11-03 22:26:10,876 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:11,252 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:11,630 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:12,006 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:12,383 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:12,759 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:13,136 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:13,460 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client7 allow already in process, so waiting to check for reconnects
2016-11-03 22:26:13,461 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client7 allow already in process, so waiting to check for reconnects
2016-11-03 22:26:13,461 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client7 allow already in process, so waiting to check for reconnects
2016-11-03 22:26:13,461 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client7 allow already in process, so waiting to check for reconnects
2016-11-03 22:26:13,461 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client7 allow already in process, so waiting to check for reconnects
2016-11-03 22:26:13,461 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client7 allow already in process, so waiting to check for reconnects
2016-11-03 22:26:13,461 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client7 allow already in process, so waiting to check for reconnects
2016-11-03 22:26:13,461 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Client7 nodereg is odict_items([('Node1C', HA(host='35.161.137.38', port=9702)), ('Node2C', HA(host='35.161.111.17', port=9704)), ('Node3C', HA(host='35.161.122.249', port=9706)), ('Node4C', HA(host='35.160.153.163', port=9708)), ('Node5C', HA(host='54.147.219.106', port=9710)), ('Node6C', HA(host='52.199.48.127', port=9712)), ('Node7C', HA(host='54.169.186.146', port=9714))])
2016-11-03 22:26:13,461 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Client7 nodestack is ['Node4C', 'Node3C', 'Node7C', 'Node6C', 'Node5C', 'Node2C', 'Node1C']
2016-11-03 22:26:13,461 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 6 ('35.160.153.163', 9708)
2016-11-03 22:26:13,462 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 4 ('35.161.122.249', 9706)
2016-11-03 22:26:13,462 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 7 ('54.169.186.146', 9714)
2016-11-03 22:26:13,462 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 2 ('52.199.48.127', 9712)
2016-11-03 22:26:13,462 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 3 ('54.147.219.106', 9710)
2016-11-03 22:26:13,462 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 5 ('35.161.111.17', 9704)
2016-11-03 22:26:13,462 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client7 matched remote is 8 ('35.161.137.38', 9702)
2016-11-03 22:26:13,462 | DEBUG    | stacked.py           (490) | maintainConnections | Client7 next check for retries in 6.00 seconds
2016-11-03 22:26:13,512 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:13,888 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:14,266 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Allower Client7. Redo Hello with Node4C in 1 at 7.6275345089961775
Allower Client7. Redo Hello with Node3C in 1 at 7.6275345089961775
Allower Client7. Redo Hello with Node7C in 1 at 7.6275345089961775
Allower Client7. Redo Hello with Node6C in 1 at 7.655339381999511
Allower Client7. Redo Hello with Node5C in 1 at 7.655339381999511
Allower Client7. Redo Hello with Node2C in 1 at 7.655339381999511
Allower Client7. Redo Hello with Node1C in 1 at 7.673487575993931
2016-11-03 22:26:14,643 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:15,019 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:15,395 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:15,772 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:16,149 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:16,525 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:16,901 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:17,280 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:17,656 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:18,032 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:18,409 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:18,785 | WARNING  | eventually.py        (133) | eventually | partial(checkIfConnectedToAll) last try...
2016-11-03 22:26:18,786 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:26:18,786 | ERROR    | eventually.py        (156) | eventually | partial(checkIfConnectedToAll) failed; not trying any more because 7.499988634001056 seconds have passed; args were ()
2016-11-03 22:26:18,786 | DEBUG    | eventually.py        (79) | eventuallyAll | a coro partial(checkIfConnectedToAll) timed out without succeeding; fail count: 1, acceptable: 0
2016-11-03 22:26:18,786 | ERROR    | looper.py            (230) | wrapper | Error while running coroutine eventuallyAll: Exception('Not connected to any',)
2016-11-03 22:26:18,786 | INFO     | looper.py            (253) | shutdown | Looper shutting down now...
2016-11-03 22:26:18,794 | DEBUG    | motor.py             (34) | set_status | Client7 changing status from starting to stopping
2016-11-03 22:26:18,794 | INFO     | stacked.py           (82) | stop | stack Client7 stopped
2016-11-03 22:26:18,794 | DEBUG    | motor.py             (34) | set_status | Client7 changing status from stopping to stopped
2016-11-03 22:26:18,794 | INFO     | looper.py            (260) | shutdown | Looper shut down in 0.008 seconds.
Traceback (most recent call last):
  File "gen_load_ratcheting", line 331, in <module>
    main(commandLineArgs)
  File "gen_load_ratcheting", line 314, in main
    retryWait=RETRY_WAIT))
  File "/home/lovesh/dev/evernym/plenum-priv/plenum/common/looper.py", line 240, in run
    return self.loop.run_until_complete(what)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/lovesh/dev/evernym/plenum-priv/plenum/common/looper.py", line 231, in wrapper
    raise ex
  File "/home/lovesh/dev/evernym/plenum-priv/plenum/common/looper.py", line 219, in wrapper
    results.append(await coro)
  File "/home/lovesh/dev/evernym/plenum-priv/plenum/test/eventually.py", line 74, in eventuallyAll
    verbose=False)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/lovesh/dev/evernym/plenum-priv/plenum/test/eventually.py", line 157, in eventually
    raise ex
  File "/home/lovesh/dev/evernym/plenum-priv/plenum/test/eventually.py", line 135, in eventually
    res = coroFunc(*args)
  File "gen_load_ratcheting", line 219, in checkIfConnectedToAll
    raise Exception("Not connected to any")
Exception: Not connected to any
2016-11-03 22:26:18,830 | DEBUG    | base_events.py       (410) | close | Close <_UnixSelectorEventLoop running=False closed=False debug=True>
