2016-11-03 21:36:43,367 | INFO     | log.py               (128) | setupLogging | Choosing RAET log level 1
2016-11-03 21:36:45,780 | DEBUG    | testable.py          (126) | decorator | in SpyableTestClient added spy on __init__
2016-11-03 21:36:45,781 | WARNING  | testable.py          (134) | decorator | method <function Client.handleOneNodeMsg at 0x7fa4a8621ea0> not found, so no spy added
2016-11-03 21:36:45,793 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on __init__
2016-11-03 21:36:45,794 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterReqLatencyTooHigh
2016-11-03 21:36:45,794 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterThroughputTooLow
2016-11-03 21:36:45,794 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on sendThroughput
2016-11-03 21:36:45,804 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on __init__
2016-11-03 21:36:45,804 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on catchupCompleted
2016-11-03 21:36:45,804 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on processConsistencyProofReq
2016-11-03 21:36:45,805 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on startCatchUpProcess
2016-11-03 21:36:45,820 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on __init__
2016-11-03 21:36:45,820 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on addToPrePrepares
2016-11-03 21:36:45,820 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canProcessPrePrepare
2016-11-03 21:36:45,820 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canSendPrepare
2016-11-03 21:36:45,820 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doOrder
2016-11-03 21:36:45,820 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrePrepare
2016-11-03 21:36:45,820 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrepare
2016-11-03 21:36:45,821 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on isValidPrepare
2016-11-03 21:36:45,821 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on orderPendingCommit
2016-11-03 21:36:45,821 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processCommit
2016-11-03 21:36:45,821 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrePrepare
2016-11-03 21:36:45,821 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrepare
2016-11-03 21:36:45,829 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on __init__
2016-11-03 21:36:45,829 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on checkPerformance
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on decidePrimaries
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on discard
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on eatTestMsg
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on forward
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleInvalidClientMsg
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleOneNodeMsg
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToClientInBox
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToNodeInBox
2016-11-03 21:36:45,831 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processInstanceChange
2016-11-03 21:36:45,831 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processOrdered
2016-11-03 21:36:45,831 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processPropagate
2016-11-03 21:36:45,835 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processRequest
2016-11-03 21:36:45,836 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on propagate
2016-11-03 21:36:45,836 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousClient
2016-11-03 21:36:45,836 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousNode
2016-11-03 21:36:45,836 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on send
2016-11-03 21:36:45,836 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on sendInstanceChange
2016-11-03 21:36:45,836 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on startViewChange
Loading module /home/lovesh/.virtualenvs/sovrin-dev/lib/python3.5/site-packages/anoncreds_dev-0.1.8-py3.5.egg/config/config-crypto-example1.py
Module loaded.
2016-11-03 21:36:46,362 | DEBUG    | gen_load_ratcheting  (280) | main | Results file: /home/lovesh/dev/evernym/sovrin-priv/scripts/perf_results_1_2_1478189206.csv
2016-11-03 21:36:46,362 | INFO     | gen_load_ratcheting  (136) | _spawnClient | Seed for client Claaaa1 is b'0000000000000000000000000Claaaa1', its len is 32
2016-11-03 21:36:46,367 | DEBUG    | ledger.py            (164) | start | Starting ledger...
2016-11-03 21:36:46,367 | DEBUG    | ledger.py            (69) | recoverTree | Recovering tree from transaction log
2016-11-03 21:36:46,401 | INFO     | client.py            (121) | __init__ | Client Claaaa1 initialized with the following node registry:
2016-11-03 21:36:46,401 | INFO     | client.py            (128) | __init__ |     EvernymV1C      listens at 52.33.22.91    on port 9722
2016-11-03 21:36:46,401 | INFO     | client.py            (128) | __init__ |     EvernymV2C      listens at 52.38.24.189   on port 9724
2016-11-03 21:36:46,401 | INFO     | client.py            (128) | __init__ |     WSECUC          listens at 13.93.218.255  on port 9726
2016-11-03 21:36:46,401 | INFO     | client.py            (128) | __init__ |     BIGC            listens at 52.160.103.164 on port 9728
2016-11-03 21:36:46,401 | INFO     | client.py            (128) | __init__ |     RespectNetworkC listens at 54.173.9.185   on port 9730
2016-11-03 21:36:46,401 | INFO     | client.py            (128) | __init__ |     FCUC            listens at 69.144.146.171 on port 9734
2016-11-03 21:36:46,401 | INFO     | client.py            (128) | __init__ |     BYUC            listens at 54.193.6.155   on port 9745
2016-11-03 21:36:46,401 | DEBUG    | plugin_helper.py     (25) | loadPlugins | Plugin loading started to load plugins from basedir: /home/lovesh/.sovrin
2016-11-03 21:36:47,064 | DEBUG    | plugin_helper.py     (68) | loadPlugins | Total plugins loaded from basedir /home/lovesh/.sovrin are : 1
2016-11-03 21:36:47,064 | DEBUG    | client.py            (148) | __init__ | total plugins loaded in client: 1
2016-11-03 21:36:47,065 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
2016-11-03 21:36:47,065 | DEBUG    | looper.py            (121) | __init__ | Setting handler for SIGINT
2016-11-03 21:36:47,065 | DEBUG    | motor.py             (34) | set_status | Claaaa1 changing status from stopped to starting
2016-11-03 21:36:47,065 | INFO     | stacked.py           (75) | start | stack Claaaa1 starting at ('0.0.0.0', 6057) in always mode
2016-11-03 21:36:47,066 | INFO     | stacked.py           (851) | start | Claaaa1 listening for other nodes at 0.0.0.0:6057
2016-11-03 21:36:47,066 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa1 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:47,066 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa1 nodestack is []
2016-11-03 21:36:47,066 | DEBUG    | stacked.py           (504) | connectToMissing | Claaaa1 found the following missing connections: BIGC, EvernymV2C, WSECUC, FCUC, RespectNetworkC, BYUC, EvernymV1C
2016-11-03 21:36:47,207 | INFO     | stacked.py           (456) | connect | Claaaa1 looking for BIGC at 52.160.103.164:9728
2016-11-03 21:36:47,260 | INFO     | stacked.py           (456) | connect | Claaaa1 looking for EvernymV2C at 52.38.24.189:9724
2016-11-03 21:36:47,388 | INFO     | stacked.py           (456) | connect | Claaaa1 looking for WSECUC at 13.93.218.255:9726
2016-11-03 21:36:47,640 | INFO     | stacked.py           (456) | connect | Claaaa1 looking for FCUC at 69.144.146.171:9734
2016-11-03 21:36:47,662 | INFO     | stacked.py           (456) | connect | Claaaa1 looking for RespectNetworkC at 54.173.9.185:9730
2016-11-03 21:36:47,716 | INFO     | stacked.py           (456) | connect | Claaaa1 looking for BYUC at 54.193.6.155:9745
2016-11-03 21:36:47,738 | INFO     | stacked.py           (456) | connect | Claaaa1 looking for EvernymV1C at 52.33.22.91:9722
2016-11-03 21:36:47,738 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa1 next check for retries in 6.00 seconds
2016-11-03 21:36:47,743 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 21:36:48,159 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Staler 'Claaaa1'. Stale transaction '1' packet 'None' from '('54.193.6.155', 9745)' in 1 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '0'
Staler 'Claaaa1'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 1 at 1.8005801029939903
Staler 'Claaaa1'. Stale transaction '1' packet 'None' from '('54.173.9.185', 9730)' in 1 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '0'
Staler 'Claaaa1'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 1 at 1.8600761449997663
Staler 'Claaaa1'. Stale transaction '1' packet 'None' from '('52.33.22.91', 9722)' in 1 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '0'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 1 at 1.8600761449997663
Staler 'Claaaa1'. Stale transaction '1' packet 'None' from '('52.38.24.189', 9724)' in 1 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '0'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 1 at 1.8906932619938743
Staler 'Claaaa1'. Stale transaction '1' packet 'None' from '('52.33.22.91', 9722)' in 1 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '0'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 1 at 2.062399832997471
Staler 'Claaaa1'. Stale transaction '1' packet 'None' from '('52.38.24.189', 9724)' in 1 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '0'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 1 at 2.090820855999482
2016-11-03 21:36:48,535 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 21:36:48,726 | DEBUG    | stacked.py           (294) | conns | Claaaa1's connection changed from set() to {'RespectNetworkC'}
2016-11-03 21:36:48,726 | INFO     | stacked.py           (320) | _connsChanged | Claaaa1 now connected to RespectNetworkC
2016-11-03 21:36:48,726 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa1 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to RespectNetworkC
2016-11-03 21:36:48,821 | DEBUG    | stacked.py           (294) | conns | Claaaa1's connection changed from {'RespectNetworkC'} to {'RespectNetworkC', 'BYUC'}
2016-11-03 21:36:48,821 | INFO     | stacked.py           (320) | _connsChanged | Claaaa1 now connected to BYUC
2016-11-03 21:36:48,821 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa1 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BYUC
2016-11-03 21:36:48,915 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 2 / 7 nodes
2016-11-03 21:36:48,963 | DEBUG    | stacked.py           (294) | conns | Claaaa1's connection changed from {'RespectNetworkC', 'BYUC'} to {'RespectNetworkC', 'BYUC', 'EvernymV1C'}
2016-11-03 21:36:48,963 | INFO     | stacked.py           (320) | _connsChanged | Claaaa1 now connected to EvernymV1C
2016-11-03 21:36:48,963 | DEBUG    | motor.py             (34) | set_status | Claaaa1 changing status from starting to started_hungry
2016-11-03 21:36:48,964 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa1 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV1C
2016-11-03 21:36:48,983 | DEBUG    | stacked.py           (294) | conns | Claaaa1's connection changed from {'RespectNetworkC', 'BYUC', 'EvernymV1C'} to {'RespectNetworkC', 'EvernymV2C', 'EvernymV1C', 'BYUC'}
2016-11-03 21:36:48,983 | INFO     | stacked.py           (320) | _connsChanged | Claaaa1 now connected to EvernymV2C
2016-11-03 21:36:48,983 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa1 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV2C
Staler 'Claaaa1'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '0'
Staler 'Claaaa1'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.5942294880005647
Staler 'Claaaa1'. Stale transaction '3' packet '1' from '('54.193.6.155', 9745)' in 2 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '433'
Staler 'Claaaa1'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 2 at 2.646319200997823
2016-11-03 21:36:49,072 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa1 got msg from node RespectNetworkC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,073 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa1 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from RespectNetworkC
2016-11-03 21:36:49,073 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa1 cannot start catchup since received only 1 consistency proofs but need at least 3
Staler 'Claaaa1'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '0'
Staler 'Claaaa1'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.6965907939957106
Staler 'Claaaa1'. Stale transaction '3' packet '1' from '('52.33.22.91', 9722)' in 2 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '465'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 2 at 2.776602403995639
Staler 'Claaaa1'. Stale transaction '3' packet '1' from '('52.38.24.189', 9724)' in 2 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '481'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 2 at 2.8466287369956262
2016-11-03 21:36:49,258 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa1 got msg from node BYUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,259 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa1 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BYUC
2016-11-03 21:36:49,259 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa1 scheduling action functools.partial(<bound method LedgerManager.checkIfCPsNeeded of Claaaa1>, 0) with id 1 to run in 30 seconds
2016-11-03 21:36:49,259 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa1 cannot start catchup since received only 2 consistency proofs but need at least 3
2016-11-03 21:36:49,291 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 4 / 7 nodes
Staler 'Claaaa1'. Stale transaction '4' packet '1' from '('54.193.6.155', 9745)' in 3 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '433'
Staler 'Claaaa1'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 3 at 2.966707558000053
2016-11-03 21:36:49,539 | DEBUG    | stacked.py           (294) | conns | Claaaa1's connection changed from {'RespectNetworkC', 'EvernymV2C', 'EvernymV1C', 'BYUC'} to {'FCUC', 'RespectNetworkC', 'EvernymV2C', 'EvernymV1C', 'BYUC'}
2016-11-03 21:36:49,540 | INFO     | stacked.py           (320) | _connsChanged | Claaaa1 now connected to FCUC
2016-11-03 21:36:49,540 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa1 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to FCUC
Staler 'Claaaa1'. Stale transaction '4' packet '1' from '('52.33.22.91', 9722)' in 3 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '465'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 3 at 3.212340056998073
2016-11-03 21:36:49,626 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa1 got msg from node EvernymV1C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,626 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa1 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV1C
2016-11-03 21:36:49,627 | DEBUG    | ledger_manager.py    (576) | canStartCatchUpProcess | Claaaa1 deciding on the basis of CPs {'RespectNetworkC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'BYUC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'EvernymV1C': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='])} and f 1
2016-11-03 21:36:49,627 | DEBUG    | ledger_manager.py    (656) | startCatchUpProcess | Claaaa1 started catching up with consistency proof CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=('Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='))
2016-11-03 21:36:49,627 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa1 scheduling action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa1>, 0) with id 2 to run in 5.1 seconds
2016-11-03 21:36:49,628 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa1 sending msg OrderedDict([('op', 'CATCHUP_REQ'), ('ledgerType', 0), ('seqNoStart', 8), ('seqNoEnd', 8)]) to FCUC
2016-11-03 21:36:49,635 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa1 got msg from node EvernymV2C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,635 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa1 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV2C
2016-11-03 21:36:49,635 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa1 cannot process consistency proof since in state 2 and canSync is True
2016-11-03 21:36:49,668 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa1'. Stale transaction '4' packet '1' from '('52.38.24.189', 9724)' in 3 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '481'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 3 at 3.3393632219958818
Staler 'Claaaa1'. Stale transaction '3' packet '1' from '('69.144.146.171', 9734)' in 2 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '334'
Staler 'Claaaa1'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 2 at 3.3721868759967037
2016-11-03 21:36:49,882 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa1 got msg from node FCUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,884 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa1 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from FCUC
2016-11-03 21:36:49,884 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa1 cannot process consistency proof since in state 2 and canSync is True
2016-11-03 21:36:49,948 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa1 got msg from node FCUC: {'op': 'CATCHUP_REP', 'ledgerType': 0, 'txns': {'8': {'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'type': 'CHANGE_HA', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'data': {'node_port': 9725, 'client_ip': '40.121.149.41', 'node_ip': '40.121.149.41', 'client_port': 9726, 'alias': 'WSECU'}, 'txnTime': 1478157003369.697, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'reqId': 1478156921805694}}, 'consProof': []}
2016-11-03 21:36:49,948 | DEBUG    | ledger_manager.py    (384) | processCatchupRep | Claaaa1 received catchup reply from FCUC: CATCHUP_REP(ledgerType=0, txns={'8': {'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'type': 'CHANGE_HA', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'data': {'node_port': 9725, 'client_ip': '40.121.149.41', 'node_ip': '40.121.149.41', 'client_port': 9726, 'alias': 'WSECU'}, 'txnTime': 1478157003369.697, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'reqId': 1478156921805694}}, consProof=[])
2016-11-03 21:36:49,948 | DEBUG    | ledger_manager.py    (390) | processCatchupRep | Claaaa1 found 1 transactions in the catchup from FCUC
2016-11-03 21:36:49,948 | DEBUG    | ledger_manager.py    (399) | processCatchupRep | Claaaa1 merging all received catchups
2016-11-03 21:36:49,948 | DEBUG    | ledger_manager.py    (405) | processCatchupRep | Claaaa1 merged catchups, there are 1 of them now, from 8 to 8
2016-11-03 21:36:49,949 | DEBUG    | ledger_manager.py    (496) | hasValidCatchupReplies | Claaaa1 verifying proof for 8, 8, b'\xc8v\xe37\xc5\xb5\xf0S\x827m\x9d\xe9\xbf\x8b\xc9\xc4\xd7\xaf)\x0b\xb5\xfa\x06\x90\xb1Ed\xb8\xb9ya', b'\xd7\x99p\xfar\xf5\xd9\x9e\xb8\xd2\x05\xe3\x81\x9f\x8c\xdd2;\xfd\xab(\xf6\xbcU\tNW\xc0jDMV', []
2016-11-03 21:36:49,949 | INFO     | ledger_manager.py    (505) | hasValidCatchupReplies | Claaaa1 could not verify catchup reply CATCHUP_REP(ledgerType=0, txns={'8': {'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'type': 'CHANGE_HA', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'data': {'node_port': 9725, 'client_ip': '40.121.149.41', 'node_ip': '40.121.149.41', 'client_port': 9726, 'alias': 'WSECU'}, 'txnTime': 1478157003369.697, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'reqId': 1478156921805694}}, consProof=[]) since Inconsistency: different root hashes for the same tree size
2016-11-03 21:36:49,949 | DEBUG    | ledger_manager.py    (413) | processCatchupRep | Claaaa1 processed 0 catchup replies with sequence numbers []
2016-11-03 21:36:50,044 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa1'. Stale transaction '4' packet '1' from '('69.144.146.171', 9734)' in 3 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '334'
Staler 'Claaaa1'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 3 at 3.6955746479943627
2016-11-03 21:36:50,421 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:50,798 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa1'. Stale transaction '1' packet 'None' from '('52.160.103.164', 9728)' in 1 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '0'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 1 at 4.60616691299947
2016-11-03 21:36:51,176 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,552 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,930 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,306 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,682 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,059 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,072 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Claaaa1 allow already in process, so waiting to check for reconnects
2016-11-03 21:36:53,072 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa1 join already in process, so waiting to check for reconnects
2016-11-03 21:36:53,072 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa1 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:53,072 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa1 nodestack is ['BIGC', 'EvernymV2C', 'estate_857ebeeea1df11e6ac2c6807152028e4', 'FCUC', 'RespectNetworkC', 'BYUC', 'EvernymV1C']
2016-11-03 21:36:53,072 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa1 matched remote is 2 ('52.160.103.164', 9728)
2016-11-03 21:36:53,072 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa1 matched remote is 3 ('52.38.24.189', 9724)
2016-11-03 21:36:53,072 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa1 unmatched remote is 4 ('13.93.218.255', 9726)
2016-11-03 21:36:53,073 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa1 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_857ebeeea1df11e6ac2c6807152028e4
2016-11-03 21:36:53,073 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa1 matched remote is 5 ('69.144.146.171', 9734)
2016-11-03 21:36:53,073 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa1 matched remote is 6 ('54.173.9.185', 9730)
2016-11-03 21:36:53,073 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa1 matched remote is 7 ('54.193.6.155', 9745)
2016-11-03 21:36:53,073 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa1 matched remote is 8 ('52.33.22.91', 9722)
2016-11-03 21:36:53,073 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa1 next check for retries in 6.00 seconds
2016-11-03 21:36:53,435 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,811 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,011 | DEBUG    | stacked.py           (294) | conns | Claaaa1's connection changed from {'FCUC', 'RespectNetworkC', 'EvernymV2C', 'EvernymV1C', 'BYUC'} to {'EvernymV2C', 'FCUC', 'RespectNetworkC', 'EvernymV1C', 'BIGC', 'BYUC'}
2016-11-03 21:36:54,011 | INFO     | stacked.py           (320) | _connsChanged | Claaaa1 now connected to BIGC
2016-11-03 21:36:54,012 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa1 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BIGC
2016-11-03 21:36:54,188 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 6 / 7 nodes
2016-11-03 21:36:54,189 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkIfConnectedToAll) succeeded with 1.05 seconds to spare
2016-11-03 21:36:54,191 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'identifier': 'FySCX5Sr3t9fqhUQt4uuwWFAREqridpYDT2FGUuSUV9u', 'signature': None, 'operation': {'type': 'ATTRIB', 'raw': 'a5242ce06b044ca2916a7e93b0159c87fd5e25ddb576c14cbdd3f80e6fcd9d38'}, 'reqId': 1478189214190257} into identifier:FySCX5Sr3t9fqhUQt4uuwWFAREqridpYDT2FGUuSUV9u|operation:raw:a5242ce06b044ca2916a7e93b0159c87fd5e25ddb576c14cbdd3f80e6fcd9d38|type:ATTRIB|reqId:1478189214190257
2016-11-03 21:36:54,191 | DEBUG    | client.py            (228) | submitReqs | Claaaa1 pending request since in mode 1 and connected to {'EvernymV2C', 'FCUC', 'RespectNetworkC', 'EvernymV1C', 'BIGC', 'BYUC'} nodes
2016-11-03 21:36:54,191 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'signature': '3EXTEXa5jsG2MFURvNh6jWiQW5esnfErVQik5GXDiSwcqsqvmCu7UcKziQoEJyBTWHw8bBjDW2CRdMHFgeWbqDXL', 'reqId': 1478189214190257, 'identifier': 'FySCX5Sr3t9fqhUQt4uuwWFAREqridpYDT2FGUuSUV9u', 'operation': {'type': 'ATTRIB', 'raw': '{"V6Fx5AlydCI9unLEJsTR_531242": "523247926700_aspmhxj0T6kJEMWwiZLql21P8oRuKN97YDBtOHecUQXbAn5Iyf"}'}}
2016-11-03 21:36:54,192 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa1 sending request Request: {'signature': '3EXTEXa5jsG2MFURvNh6jWiQW5esnfErVQik5GXDiSwcqsqvmCu7UcKziQoEJyBTWHw8bBjDW2CRdMHFgeWbqDXL', 'reqId': 1478189214190257, 'identifier': 'FySCX5Sr3t9fqhUQt4uuwWFAREqridpYDT2FGUuSUV9u', 'operation': {'type': 'ATTRIB', 'raw': '{"V6Fx5AlydCI9unLEJsTR_531242": "523247926700_aspmhxj0T6kJEMWwiZLql21P8oRuKN97YDBtOHecUQXbAn5Iyf"}'}}
2016-11-03 21:36:54,734 | DEBUG    | has_action_queue.py  (60) | _serviceActions | Claaaa1 running action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa1>, 0) with id 2
Staler 'Claaaa1'. Stale transaction '3' packet '1' from '('52.160.103.164', 9728)' in 2 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '474'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 2 at 9.08274692199484
Staler 'Claaaa1'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '474'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 11.133738301999983
Staler 'Claaaa1'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '474'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 11.133738301999983
2016-11-03 21:36:59,074 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa1 join already in process, so waiting to check for reconnects
2016-11-03 21:36:59,075 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa1 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:59,075 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa1 nodestack is ['BIGC', 'EvernymV2C', 'estate_857ebeeea1df11e6ac2c6807152028e4', 'FCUC', 'RespectNetworkC', 'BYUC', 'EvernymV1C']
2016-11-03 21:36:59,075 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa1 matched remote is 2 ('52.160.103.164', 9728)
2016-11-03 21:36:59,075 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa1 matched remote is 3 ('52.38.24.189', 9724)
2016-11-03 21:36:59,075 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa1 unmatched remote is 4 ('13.93.218.255', 9726)
2016-11-03 21:36:59,075 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa1 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_857ebeeea1df11e6ac2c6807152028e4
2016-11-03 21:36:59,075 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa1 matched remote is 5 ('69.144.146.171', 9734)
2016-11-03 21:36:59,076 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa1 matched remote is 6 ('54.173.9.185', 9730)
2016-11-03 21:36:59,076 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa1 matched remote is 7 ('54.193.6.155', 9745)
2016-11-03 21:36:59,076 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa1 matched remote is 8 ('52.33.22.91', 9722)
2016-11-03 21:36:59,076 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa1 next check for retries in 6.00 seconds
2016-11-03 21:36:59,228 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa1', signerId='FySCX5Sr3t9fqhUQt4uuwWFAREqridpYDT2FGUuSUV9u', reqId=1478189214190257, transactionType='ATTRIB', sentAt=1478189214.1917133, quorumAt='', latency=5.036963701248169, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:36:59,229 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.46 seconds to spare
2016-11-03 21:36:59,229 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 5.03962516784668
        Average latency: 5.036963701248169
        Throughput: 0.0
        Error rate: 0.19842745575208678
        Succeeded: 0
        Failed: 1
        Query Time: 0
        ================================
        
2016-11-03 21:36:59,229 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'identifier': 'FySCX5Sr3t9fqhUQt4uuwWFAREqridpYDT2FGUuSUV9u', 'signature': None, 'operation': {'type': 'ATTRIB', 'raw': 'afcf8ccf60a70549f844c340cfd4af98ce336e4f9d8585af42407bee5cd8d3dc'}, 'reqId': 1478189219229692} into identifier:FySCX5Sr3t9fqhUQt4uuwWFAREqridpYDT2FGUuSUV9u|operation:raw:afcf8ccf60a70549f844c340cfd4af98ce336e4f9d8585af42407bee5cd8d3dc|type:ATTRIB|reqId:1478189219229692
2016-11-03 21:36:59,230 | DEBUG    | client.py            (228) | submitReqs | Claaaa1 pending request since in mode 1 and connected to {'EvernymV2C', 'FCUC', 'RespectNetworkC', 'EvernymV1C', 'BIGC', 'BYUC'} nodes
2016-11-03 21:36:59,230 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'signature': '4CABubh7Ydr2L8StKrVfyXUFbquPcEAwXVoSoeMja4x3xvBfyYKaJkXQD8JQ5tiLsgFchnVYPF8Q9jojWcCsr8co', 'reqId': 1478189219229692, 'identifier': 'FySCX5Sr3t9fqhUQt4uuwWFAREqridpYDT2FGUuSUV9u', 'operation': {'type': 'ATTRIB', 'raw': '{"tzr0FaCQg4GjmOBEK5dk_311838": "226233091561_kO4SfpNbyIxosaiLUwPWHG2eAjXzYncmEtdrhq7l9DM35FKQvu"}'}}
2016-11-03 21:36:59,230 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa1 sending request Request: {'signature': '4CABubh7Ydr2L8StKrVfyXUFbquPcEAwXVoSoeMja4x3xvBfyYKaJkXQD8JQ5tiLsgFchnVYPF8Q9jojWcCsr8co', 'reqId': 1478189219229692, 'identifier': 'FySCX5Sr3t9fqhUQt4uuwWFAREqridpYDT2FGUuSUV9u', 'operation': {'type': 'ATTRIB', 'raw': '{"tzr0FaCQg4GjmOBEK5dk_311838": "226233091561_kO4SfpNbyIxosaiLUwPWHG2eAjXzYncmEtdrhq7l9DM35FKQvu"}'}}
Staler 'Claaaa1'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '474'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.914963800998521
Staler 'Claaaa1'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa1'. Unknown correspondent estate id '474'
Staler 'Claaaa1'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.914963800998521
2016-11-03 21:37:00,338 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa1 got msg from node BIGC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:37:00,338 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa1 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BIGC
2016-11-03 21:37:00,338 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa1 cannot process consistency proof since in state 2 and canSync is True
Stalent 'Claaaa1'. Stale transaction '0' packet '0' from '('52.160.103.164', 9728)' in 1 nacking ...
Stalent 'Claaaa1'. Unknown initiator estate id '474'
Stalent 'Claaaa1'. Do Nack of ('52.160.103.164', 9728) in 1 at 15.10844283500046
2016-11-03 21:37:04,268 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa1', signerId='FySCX5Sr3t9fqhUQt4uuwWFAREqridpYDT2FGUuSUV9u', reqId=1478189219229692, transactionType='ATTRIB', sentAt=1478189219.2301638, quorumAt='', latency=5.038494825363159, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:37:04,269 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.46 seconds to spare
2016-11-03 21:37:04,269 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 10.079688310623169
        Average latency: 5.037729263305664
        Throughput: 0.0
        Error rate: 0.19841883383359812
        Succeeded: 0
        Failed: 2
        Query Time: 0
        ================================
        
2016-11-03 21:37:04,269 | DEBUG    | gen_load_ratcheting  (326) | main | Sent 1 ATTRIB requests
2016-11-03 21:37:04,269 | INFO     | looper.py            (253) | shutdown | Looper shutting down now...
2016-11-03 21:37:04,280 | DEBUG    | motor.py             (34) | set_status | Claaaa1 changing status from started_hungry to stopping
2016-11-03 21:37:04,281 | INFO     | stacked.py           (82) | stop | stack Claaaa1 stopped
2016-11-03 21:37:04,281 | DEBUG    | motor.py             (34) | set_status | Claaaa1 changing status from stopping to stopped
2016-11-03 21:37:04,281 | INFO     | looper.py            (260) | shutdown | Looper shut down in 0.011 seconds.
2016-11-03 21:37:04,324 | DEBUG    | base_events.py       (410) | close | Close <_UnixSelectorEventLoop running=False closed=False debug=True>
