2016-11-03 21:36:43,465 | INFO     | log.py               (128) | setupLogging | Choosing RAET log level 1
2016-11-03 21:36:45,804 | DEBUG    | testable.py          (126) | decorator | in SpyableTestClient added spy on __init__
2016-11-03 21:36:45,804 | WARNING  | testable.py          (134) | decorator | method <function Client.handleOneNodeMsg at 0x7fe5c3148ea0> not found, so no spy added
2016-11-03 21:36:45,818 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on __init__
2016-11-03 21:36:45,818 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterReqLatencyTooHigh
2016-11-03 21:36:45,818 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterThroughputTooLow
2016-11-03 21:36:45,818 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on sendThroughput
2016-11-03 21:36:45,834 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on __init__
2016-11-03 21:36:45,835 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on catchupCompleted
2016-11-03 21:36:45,835 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on processConsistencyProofReq
2016-11-03 21:36:45,835 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on startCatchUpProcess
2016-11-03 21:36:45,838 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on __init__
2016-11-03 21:36:45,838 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on addToPrePrepares
2016-11-03 21:36:45,838 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canProcessPrePrepare
2016-11-03 21:36:45,838 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canSendPrepare
2016-11-03 21:36:45,838 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doOrder
2016-11-03 21:36:45,838 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrePrepare
2016-11-03 21:36:45,838 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrepare
2016-11-03 21:36:45,839 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on isValidPrepare
2016-11-03 21:36:45,839 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on orderPendingCommit
2016-11-03 21:36:45,839 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processCommit
2016-11-03 21:36:45,839 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrePrepare
2016-11-03 21:36:45,839 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrepare
2016-11-03 21:36:45,843 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on __init__
2016-11-03 21:36:45,843 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on checkPerformance
2016-11-03 21:36:45,843 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on decidePrimaries
2016-11-03 21:36:45,843 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on discard
2016-11-03 21:36:45,843 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on eatTestMsg
2016-11-03 21:36:45,843 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on forward
2016-11-03 21:36:45,843 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleInvalidClientMsg
2016-11-03 21:36:45,844 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleOneNodeMsg
2016-11-03 21:36:45,844 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToClientInBox
2016-11-03 21:36:45,844 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToNodeInBox
2016-11-03 21:36:45,844 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processInstanceChange
2016-11-03 21:36:45,844 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processOrdered
2016-11-03 21:36:45,844 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processPropagate
2016-11-03 21:36:45,844 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processRequest
2016-11-03 21:36:45,844 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on propagate
2016-11-03 21:36:45,844 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousClient
2016-11-03 21:36:45,845 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousNode
2016-11-03 21:36:45,845 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on send
2016-11-03 21:36:45,845 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on sendInstanceChange
2016-11-03 21:36:45,845 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on startViewChange
Loading module /home/lovesh/.virtualenvs/sovrin-dev/lib/python3.5/site-packages/anoncreds_dev-0.1.8-py3.5.egg/config/config-crypto-example1.py
Module loaded.
2016-11-03 21:36:46,453 | DEBUG    | gen_load_ratcheting  (280) | main | Results file: /home/lovesh/dev/evernym/sovrin-priv/scripts/perf_results_1_2_1478189206.csv
2016-11-03 21:36:46,454 | INFO     | gen_load_ratcheting  (136) | _spawnClient | Seed for client Claaaa6 is b'0000000000000000000000000Claaaa6', its len is 32
2016-11-03 21:36:46,455 | DEBUG    | ledger.py            (164) | start | Starting ledger...
2016-11-03 21:36:46,455 | DEBUG    | ledger.py            (69) | recoverTree | Recovering tree from transaction log
2016-11-03 21:36:46,489 | INFO     | client.py            (121) | __init__ | Client Claaaa6 initialized with the following node registry:
2016-11-03 21:36:46,489 | INFO     | client.py            (128) | __init__ |     EvernymV1C      listens at 52.33.22.91    on port 9722
2016-11-03 21:36:46,489 | INFO     | client.py            (128) | __init__ |     EvernymV2C      listens at 52.38.24.189   on port 9724
2016-11-03 21:36:46,489 | INFO     | client.py            (128) | __init__ |     WSECUC          listens at 13.93.218.255  on port 9726
2016-11-03 21:36:46,489 | INFO     | client.py            (128) | __init__ |     BIGC            listens at 52.160.103.164 on port 9728
2016-11-03 21:36:46,490 | INFO     | client.py            (128) | __init__ |     RespectNetworkC listens at 54.173.9.185   on port 9730
2016-11-03 21:36:46,490 | INFO     | client.py            (128) | __init__ |     FCUC            listens at 69.144.146.171 on port 9734
2016-11-03 21:36:46,490 | INFO     | client.py            (128) | __init__ |     BYUC            listens at 54.193.6.155   on port 9745
2016-11-03 21:36:46,490 | DEBUG    | plugin_helper.py     (25) | loadPlugins | Plugin loading started to load plugins from basedir: /home/lovesh/.sovrin
2016-11-03 21:36:47,180 | DEBUG    | plugin_helper.py     (68) | loadPlugins | Total plugins loaded from basedir /home/lovesh/.sovrin are : 1
2016-11-03 21:36:47,180 | DEBUG    | client.py            (148) | __init__ | total plugins loaded in client: 1
2016-11-03 21:36:47,180 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
2016-11-03 21:36:47,181 | DEBUG    | looper.py            (121) | __init__ | Setting handler for SIGINT
2016-11-03 21:36:47,181 | DEBUG    | motor.py             (34) | set_status | Claaaa6 changing status from stopped to starting
2016-11-03 21:36:47,181 | INFO     | stacked.py           (75) | start | stack Claaaa6 starting at ('0.0.0.0', 5849) in always mode
2016-11-03 21:36:47,181 | INFO     | stacked.py           (851) | start | Claaaa6 listening for other nodes at 0.0.0.0:5849
2016-11-03 21:36:47,181 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa6 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:47,181 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa6 nodestack is []
2016-11-03 21:36:47,181 | DEBUG    | stacked.py           (504) | connectToMissing | Claaaa6 found the following missing connections: WSECUC, EvernymV2C, EvernymV1C, RespectNetworkC, BIGC, FCUC, BYUC
2016-11-03 21:36:47,583 | INFO     | stacked.py           (456) | connect | Claaaa6 looking for WSECUC at 13.93.218.255:9726
2016-11-03 21:36:47,640 | INFO     | stacked.py           (456) | connect | Claaaa6 looking for EvernymV2C at 52.38.24.189:9724
2016-11-03 21:36:47,661 | INFO     | stacked.py           (456) | connect | Claaaa6 looking for EvernymV1C at 52.33.22.91:9722
2016-11-03 21:36:47,717 | INFO     | stacked.py           (456) | connect | Claaaa6 looking for RespectNetworkC at 54.173.9.185:9730
2016-11-03 21:36:47,736 | INFO     | stacked.py           (456) | connect | Claaaa6 looking for BIGC at 52.160.103.164:9728
2016-11-03 21:36:47,985 | INFO     | stacked.py           (456) | connect | Claaaa6 looking for FCUC at 69.144.146.171:9734
2016-11-03 21:36:48,039 | INFO     | stacked.py           (456) | connect | Claaaa6 looking for BYUC at 54.193.6.155:9745
2016-11-03 21:36:48,040 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa6 next check for retries in 6.00 seconds
2016-11-03 21:36:48,043 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Staler 'Claaaa6'. Stale transaction '1' packet 'None' from '('54.173.9.185', 9730)' in 1 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '0'
Staler 'Claaaa6'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 1 at 1.89296430000104
Staler 'Claaaa6'. Stale transaction '1' packet 'None' from '('54.193.6.155', 9745)' in 1 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '0'
Staler 'Claaaa6'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 1 at 1.89296430000104
2016-11-03 21:36:48,419 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Staler 'Claaaa6'. Stale transaction '1' packet 'None' from '('52.38.24.189', 9724)' in 1 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '0'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 1 at 1.9324857839965262
Staler 'Claaaa6'. Stale transaction '1' packet 'None' from '('52.33.22.91', 9722)' in 1 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '0'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 1 at 1.9324857839965262
2016-11-03 21:36:48,795 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 21:36:48,894 | DEBUG    | stacked.py           (294) | conns | Claaaa6's connection changed from set() to {'BYUC'}
2016-11-03 21:36:48,894 | INFO     | stacked.py           (320) | _connsChanged | Claaaa6 now connected to BYUC
2016-11-03 21:36:48,895 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa6 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BYUC
2016-11-03 21:36:48,932 | DEBUG    | stacked.py           (294) | conns | Claaaa6's connection changed from {'BYUC'} to {'RespectNetworkC', 'BYUC'}
2016-11-03 21:36:48,933 | INFO     | stacked.py           (320) | _connsChanged | Claaaa6 now connected to RespectNetworkC
2016-11-03 21:36:48,933 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa6 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to RespectNetworkC
2016-11-03 21:36:48,986 | DEBUG    | stacked.py           (294) | conns | Claaaa6's connection changed from {'RespectNetworkC', 'BYUC'} to {'EvernymV1C', 'RespectNetworkC', 'BYUC'}
2016-11-03 21:36:48,986 | INFO     | stacked.py           (320) | _connsChanged | Claaaa6 now connected to EvernymV1C
2016-11-03 21:36:48,987 | DEBUG    | motor.py             (34) | set_status | Claaaa6 changing status from starting to started_hungry
2016-11-03 21:36:48,987 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa6 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV1C
Staler 'Claaaa6'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '0'
Staler 'Claaaa6'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.5436507139966125
2016-11-03 21:36:49,052 | DEBUG    | stacked.py           (294) | conns | Claaaa6's connection changed from {'EvernymV1C', 'RespectNetworkC', 'BYUC'} to {'EvernymV1C', 'RespectNetworkC', 'EvernymV2C', 'BYUC'}
2016-11-03 21:36:49,052 | INFO     | stacked.py           (320) | _connsChanged | Claaaa6 now connected to EvernymV2C
2016-11-03 21:36:49,052 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa6 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV2C
Staler 'Claaaa6'. Stale transaction '3' packet '1' from '('54.193.6.155', 9745)' in 2 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '439'
Staler 'Claaaa6'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 2 at 2.6098310469969874
Staler 'Claaaa6'. Stale transaction '3' packet '1' from '('54.173.9.185', 9730)' in 2 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '478'
Staler 'Claaaa6'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 2 at 2.63389660899702
2016-11-03 21:36:49,171 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 4 / 7 nodes
Staler 'Claaaa6'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '0'
Staler 'Claaaa6'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.7503193029988324
2016-11-03 21:36:49,292 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa6 got msg from node RespectNetworkC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,292 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa6 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from RespectNetworkC
2016-11-03 21:36:49,292 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa6 cannot start catchup since received only 1 consistency proofs but need at least 3
Staler 'Claaaa6'. Stale transaction '3' packet '1' from '('52.33.22.91', 9722)' in 2 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '471'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 2 at 2.8155344249971677
2016-11-03 21:36:49,314 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa6 got msg from node BYUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,314 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa6 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BYUC
2016-11-03 21:36:49,314 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa6 scheduling action functools.partial(<bound method LedgerManager.checkIfCPsNeeded of Claaaa6>, 0) with id 1 to run in 30 seconds
2016-11-03 21:36:49,314 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa6 cannot start catchup since received only 2 consistency proofs but need at least 3
Staler 'Claaaa6'. Stale transaction '4' packet '1' from '('54.193.6.155', 9745)' in 3 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '439'
Staler 'Claaaa6'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 3 at 2.8984409690019675
Staler 'Claaaa6'. Stale transaction '4' packet '1' from '('54.173.9.185', 9730)' in 3 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '478'
Staler 'Claaaa6'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 3 at 2.9191315560019575
Staler 'Claaaa6'. Stale transaction '3' packet '1' from '('52.38.24.189', 9724)' in 2 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '487'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 2 at 2.937468144002196
2016-11-03 21:36:49,548 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 4 / 7 nodes
Staler 'Claaaa6'. Stale transaction '4' packet '1' from '('52.33.22.91', 9722)' in 3 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '471'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 3 at 3.123214195999026
2016-11-03 21:36:49,623 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa6 got msg from node EvernymV1C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,624 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa6 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV1C
2016-11-03 21:36:49,624 | DEBUG    | ledger_manager.py    (576) | canStartCatchUpProcess | Claaaa6 deciding on the basis of CPs {'EvernymV1C': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'RespectNetworkC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'BYUC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='])} and f 1
2016-11-03 21:36:49,624 | DEBUG    | ledger_manager.py    (656) | startCatchUpProcess | Claaaa6 started catching up with consistency proof CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=('Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='))
2016-11-03 21:36:49,624 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa6 scheduling action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa6>, 0) with id 2 to run in 5.1 seconds
2016-11-03 21:36:49,625 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa6 sending msg OrderedDict([('op', 'CATCHUP_REQ'), ('ledgerType', 0), ('seqNoStart', 8), ('seqNoEnd', 8)]) to EvernymV1C
2016-11-03 21:36:49,649 | DEBUG    | stacked.py           (294) | conns | Claaaa6's connection changed from {'EvernymV1C', 'RespectNetworkC', 'EvernymV2C', 'BYUC'} to {'EvernymV1C', 'RespectNetworkC', 'FCUC', 'EvernymV2C', 'BYUC'}
2016-11-03 21:36:49,649 | INFO     | stacked.py           (320) | _connsChanged | Claaaa6 now connected to FCUC
2016-11-03 21:36:49,649 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa6 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to FCUC
Staler 'Claaaa6'. Stale transaction '4' packet '1' from '('52.38.24.189', 9724)' in 3 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '487'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 3 at 3.24456820100022
2016-11-03 21:36:49,745 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa6 got msg from node EvernymV2C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,745 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa6 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV2C
2016-11-03 21:36:49,745 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa6 cannot process consistency proof since in state 2 and canSync is True
Staler 'Claaaa6'. Stale transaction '3' packet '1' from '('69.144.146.171', 9734)' in 2 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '340'
Staler 'Claaaa6'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 2 at 3.4114004479997675
2016-11-03 21:36:49,924 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:49,975 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa6 got msg from node EvernymV1C: {'op': 'CATCHUP_REP', 'ledgerType': 0, 'txns': {'8': {'reqId': 1478156921805694, 'data': {'alias': 'WSECU', 'node_ip': '40.121.149.41', 'node_port': 9725, 'client_port': 9726, 'client_ip': '40.121.149.41'}, 'txnTime': 1478157003369.697, 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'type': 'CHANGE_HA', 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt'}}, 'consProof': []}
2016-11-03 21:36:49,976 | DEBUG    | ledger_manager.py    (384) | processCatchupRep | Claaaa6 received catchup reply from EvernymV1C: CATCHUP_REP(ledgerType=0, txns={'8': {'reqId': 1478156921805694, 'data': {'alias': 'WSECU', 'node_ip': '40.121.149.41', 'node_port': 9725, 'client_port': 9726, 'client_ip': '40.121.149.41'}, 'txnTime': 1478157003369.697, 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'type': 'CHANGE_HA', 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt'}}, consProof=[])
2016-11-03 21:36:49,976 | DEBUG    | ledger_manager.py    (390) | processCatchupRep | Claaaa6 found 1 transactions in the catchup from EvernymV1C
2016-11-03 21:36:49,976 | DEBUG    | ledger_manager.py    (399) | processCatchupRep | Claaaa6 merging all received catchups
2016-11-03 21:36:49,976 | DEBUG    | ledger_manager.py    (405) | processCatchupRep | Claaaa6 merged catchups, there are 1 of them now, from 8 to 8
2016-11-03 21:36:49,976 | DEBUG    | ledger_manager.py    (496) | hasValidCatchupReplies | Claaaa6 verifying proof for 8, 8, b'\xc8v\xe37\xc5\xb5\xf0S\x827m\x9d\xe9\xbf\x8b\xc9\xc4\xd7\xaf)\x0b\xb5\xfa\x06\x90\xb1Ed\xb8\xb9ya', b'\xd7\x99p\xfar\xf5\xd9\x9e\xb8\xd2\x05\xe3\x81\x9f\x8c\xdd2;\xfd\xab(\xf6\xbcU\tNW\xc0jDMV', []
2016-11-03 21:36:49,977 | INFO     | ledger_manager.py    (505) | hasValidCatchupReplies | Claaaa6 could not verify catchup reply CATCHUP_REP(ledgerType=0, txns={'8': {'reqId': 1478156921805694, 'data': {'alias': 'WSECU', 'node_ip': '40.121.149.41', 'node_port': 9725, 'client_port': 9726, 'client_ip': '40.121.149.41'}, 'txnTime': 1478157003369.697, 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'type': 'CHANGE_HA', 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt'}}, consProof=[]) since Inconsistency: different root hashes for the same tree size
2016-11-03 21:36:49,977 | DEBUG    | ledger_manager.py    (413) | processCatchupRep | Claaaa6 processed 0 catchup replies with sequence numbers []
2016-11-03 21:36:49,977 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa6 got msg from node FCUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,977 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa6 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from FCUC
2016-11-03 21:36:49,978 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa6 cannot process consistency proof since in state 2 and canSync is True
Staler 'Claaaa6'. Stale transaction '4' packet '1' from '('69.144.146.171', 9734)' in 3 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '340'
Staler 'Claaaa6'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 3 at 3.7069279689967516
2016-11-03 21:36:50,301 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:50,678 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,054 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,431 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,808 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,186 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa6'. Stale transaction '1' packet 'None' from '('52.160.103.164', 9728)' in 1 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '0'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 1 at 5.723401005001506
2016-11-03 21:36:52,563 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,940 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,191 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa6 join already in process, so waiting to check for reconnects
2016-11-03 21:36:53,191 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Claaaa6 allow already in process, so waiting to check for reconnects
2016-11-03 21:36:53,191 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa6 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:53,192 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa6 nodestack is ['estate_858dcbb2a1df11e6ac2c6807152028e4', 'EvernymV2C', 'EvernymV1C', 'RespectNetworkC', 'BIGC', 'FCUC', 'BYUC']
2016-11-03 21:36:53,192 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa6 unmatched remote is 2 ('13.93.218.255', 9726)
2016-11-03 21:36:53,192 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa6 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_858dcbb2a1df11e6ac2c6807152028e4
2016-11-03 21:36:53,192 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 3 ('52.38.24.189', 9724)
2016-11-03 21:36:53,192 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 4 ('52.33.22.91', 9722)
2016-11-03 21:36:53,192 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 5 ('54.173.9.185', 9730)
2016-11-03 21:36:53,192 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 6 ('52.160.103.164', 9728)
2016-11-03 21:36:53,192 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 7 ('69.144.146.171', 9734)
2016-11-03 21:36:53,192 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 8 ('54.193.6.155', 9745)
2016-11-03 21:36:53,192 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa6 next check for retries in 6.00 seconds
2016-11-03 21:36:53,317 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,693 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,069 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,447 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,726 | DEBUG    | has_action_queue.py  (60) | _serviceActions | Claaaa6 running action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa6>, 0) with id 2
2016-11-03 21:36:54,824 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:55,201 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:55,502 | DEBUG    | stacked.py           (294) | conns | Claaaa6's connection changed from {'EvernymV1C', 'RespectNetworkC', 'FCUC', 'EvernymV2C', 'BYUC'} to {'EvernymV1C', 'FCUC', 'EvernymV2C', 'BYUC', 'RespectNetworkC', 'BIGC'}
2016-11-03 21:36:55,502 | INFO     | stacked.py           (320) | _connsChanged | Claaaa6 now connected to BIGC
2016-11-03 21:36:55,502 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa6 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BIGC
2016-11-03 21:36:55,578 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 6 / 7 nodes
2016-11-03 21:36:55,578 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkIfConnectedToAll) succeeded with -0.04 seconds to spare
2016-11-03 21:36:55,579 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'operation': {'raw': 'ccd4fdb7e8a64577052a98c61772316e88f2d6de90379f399c760606ee963be3', 'type': 'ATTRIB'}, 'identifier': 'CB4ZQwoDCKJyLStaUkV8Z6CX6Tb86MznoVhQbgUdy4b4', 'reqId': 1478189215579272, 'signature': None} into identifier:CB4ZQwoDCKJyLStaUkV8Z6CX6Tb86MznoVhQbgUdy4b4|operation:raw:ccd4fdb7e8a64577052a98c61772316e88f2d6de90379f399c760606ee963be3|type:ATTRIB|reqId:1478189215579272
2016-11-03 21:36:55,580 | DEBUG    | client.py            (228) | submitReqs | Claaaa6 pending request since in mode 1 and connected to {'EvernymV1C', 'FCUC', 'EvernymV2C', 'BYUC', 'RespectNetworkC', 'BIGC'} nodes
2016-11-03 21:36:55,580 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'operation': {'raw': '{"URkJ2GMbwgsIOD7Hom5N_314632": "553810736511_fQPu23B7EoUKemLzHN64tZFDvCbJGA8Ssry1aIk5pcnljR9qxh"}', 'type': 'ATTRIB'}, 'identifier': 'CB4ZQwoDCKJyLStaUkV8Z6CX6Tb86MznoVhQbgUdy4b4', 'reqId': 1478189215579272, 'signature': '28xsU3iRnKp293253tvbWJo9J98EQ7JeHMreqTAjesdDqYGuc4K1tRio4QxgXYSbiNHYBVm7aGCGaNwfeozukxMo'}
2016-11-03 21:36:55,580 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa6 sending request Request: {'operation': {'raw': '{"URkJ2GMbwgsIOD7Hom5N_314632": "553810736511_fQPu23B7EoUKemLzHN64tZFDvCbJGA8Ssry1aIk5pcnljR9qxh"}', 'type': 'ATTRIB'}, 'identifier': 'CB4ZQwoDCKJyLStaUkV8Z6CX6Tb86MznoVhQbgUdy4b4', 'reqId': 1478189215579272, 'signature': '28xsU3iRnKp293253tvbWJo9J98EQ7JeHMreqTAjesdDqYGuc4K1tRio4QxgXYSbiNHYBVm7aGCGaNwfeozukxMo'}
Staler 'Claaaa6'. Stale transaction '3' packet '1' from '('52.160.103.164', 9728)' in 2 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '480'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 2 at 11.047512593999272
2016-11-03 21:36:59,192 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa6 join already in process, so waiting to check for reconnects
2016-11-03 21:36:59,192 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa6 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:59,192 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa6 nodestack is ['estate_858dcbb2a1df11e6ac2c6807152028e4', 'EvernymV2C', 'EvernymV1C', 'RespectNetworkC', 'BIGC', 'FCUC', 'BYUC']
2016-11-03 21:36:59,193 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa6 unmatched remote is 2 ('13.93.218.255', 9726)
2016-11-03 21:36:59,193 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa6 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_858dcbb2a1df11e6ac2c6807152028e4
2016-11-03 21:36:59,193 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 3 ('52.38.24.189', 9724)
2016-11-03 21:36:59,193 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 4 ('52.33.22.91', 9722)
2016-11-03 21:36:59,193 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 5 ('54.173.9.185', 9730)
2016-11-03 21:36:59,193 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 6 ('52.160.103.164', 9728)
2016-11-03 21:36:59,193 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 7 ('69.144.146.171', 9734)
2016-11-03 21:36:59,193 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 8 ('54.193.6.155', 9745)
2016-11-03 21:36:59,193 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa6 next check for retries in 6.00 seconds
Staler 'Claaaa6'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '480'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.823372487000597
Staler 'Claaaa6'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '480'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.823372487000597
Staler 'Claaaa6'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '480'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.823372487000597
2016-11-03 21:37:00,626 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa6', signerId='CB4ZQwoDCKJyLStaUkV8Z6CX6Tb86MznoVhQbgUdy4b4', reqId=1478189215579272, transactionType='ATTRIB', sentAt=1478189215.580383, quorumAt='', latency=5.046492576599121, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:37:00,627 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.45 seconds to spare
2016-11-03 21:37:00,628 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 5.049086332321167
        Average latency: 5.046492576599121
        Throughput: 0.0
        Error rate: 0.19805563505591314
        Succeeded: 0
        Failed: 1
        Query Time: 0
        ================================
        
2016-11-03 21:37:00,628 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'operation': {'raw': 'e2c62940f503299d113d4dafc63d4e2002e01ef23b6d87f876dfa3fe4ca937ce', 'type': 'ATTRIB'}, 'identifier': 'CB4ZQwoDCKJyLStaUkV8Z6CX6Tb86MznoVhQbgUdy4b4', 'reqId': 1478189220628352, 'signature': None} into identifier:CB4ZQwoDCKJyLStaUkV8Z6CX6Tb86MznoVhQbgUdy4b4|operation:raw:e2c62940f503299d113d4dafc63d4e2002e01ef23b6d87f876dfa3fe4ca937ce|type:ATTRIB|reqId:1478189220628352
2016-11-03 21:37:00,628 | DEBUG    | client.py            (228) | submitReqs | Claaaa6 pending request since in mode 1 and connected to {'EvernymV1C', 'FCUC', 'EvernymV2C', 'BYUC', 'RespectNetworkC', 'BIGC'} nodes
2016-11-03 21:37:00,629 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'operation': {'raw': '{"QNutJR9nGM1PYAVd3baw_26843": "874951102493_5lXEaj3yneGMhtOICuLYAVH410WJmRg2PkvcrpsUbZ8SwF7fDT"}', 'type': 'ATTRIB'}, 'identifier': 'CB4ZQwoDCKJyLStaUkV8Z6CX6Tb86MznoVhQbgUdy4b4', 'reqId': 1478189220628352, 'signature': '5bsbJoajYHb98t5J6T4htZHcUCtoZrSHLUJzrksr88PeDKM6jpxZMVRqRvXn1iZZJWZxyPo8Sheqgb6jhR8QWHZv'}
2016-11-03 21:37:00,629 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa6 sending request Request: {'operation': {'raw': '{"QNutJR9nGM1PYAVd3baw_26843": "874951102493_5lXEaj3yneGMhtOICuLYAVH410WJmRg2PkvcrpsUbZ8SwF7fDT"}', 'type': 'ATTRIB'}, 'identifier': 'CB4ZQwoDCKJyLStaUkV8Z6CX6Tb86MznoVhQbgUdy4b4', 'reqId': 1478189220628352, 'signature': '5bsbJoajYHb98t5J6T4htZHcUCtoZrSHLUJzrksr88PeDKM6jpxZMVRqRvXn1iZZJWZxyPo8Sheqgb6jhR8QWHZv'}
Staler 'Claaaa6'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '480'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 15.020716924002045
Staler 'Claaaa6'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '480'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 15.020716924002045
2016-11-03 21:37:01,530 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa6 got msg from node BIGC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:37:01,530 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa6 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BIGC
2016-11-03 21:37:01,530 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa6 cannot process consistency proof since in state 2 and canSync is True
Staler 'Claaaa6'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa6'. Unknown correspondent estate id '480'
Staler 'Claaaa6'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 15.602255213998433
Stalent 'Claaaa6'. Stale transaction '0' packet '0' from '('52.160.103.164', 9728)' in 1 nacking ...
Stalent 'Claaaa6'. Unknown initiator estate id '480'
Stalent 'Claaaa6'. Do Nack of ('52.160.103.164', 9728) in 1 at 15.602255213998433
2016-11-03 21:37:05,194 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa6 join already in process, so waiting to check for reconnects
2016-11-03 21:37:05,198 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa6 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:37:05,198 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa6 nodestack is ['estate_858dcbb2a1df11e6ac2c6807152028e4', 'EvernymV2C', 'EvernymV1C', 'RespectNetworkC', 'BIGC', 'FCUC', 'BYUC']
2016-11-03 21:37:05,198 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa6 unmatched remote is 2 ('13.93.218.255', 9726)
2016-11-03 21:37:05,198 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa6 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_858dcbb2a1df11e6ac2c6807152028e4
2016-11-03 21:37:05,198 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 3 ('52.38.24.189', 9724)
2016-11-03 21:37:05,199 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 4 ('52.33.22.91', 9722)
2016-11-03 21:37:05,199 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 5 ('54.173.9.185', 9730)
2016-11-03 21:37:05,199 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 6 ('52.160.103.164', 9728)
2016-11-03 21:37:05,199 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 7 ('69.144.146.171', 9734)
2016-11-03 21:37:05,199 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa6 matched remote is 8 ('54.193.6.155', 9745)
2016-11-03 21:37:05,199 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa6 next check for retries in 6.00 seconds
2016-11-03 21:37:05,672 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa6', signerId='CB4ZQwoDCKJyLStaUkV8Z6CX6Tb86MznoVhQbgUdy4b4', reqId=1478189220628352, transactionType='ATTRIB', sentAt=1478189220.6288733, quorumAt='', latency=5.043214797973633, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:37:05,672 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.46 seconds to spare
2016-11-03 21:37:05,672 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 10.093914270401001
        Average latency: 5.044853687286377
        Throughput: 0.0
        Error rate: 0.19813919025097346
        Succeeded: 0
        Failed: 2
        Query Time: 0
        ================================
        
2016-11-03 21:37:05,672 | DEBUG    | gen_load_ratcheting  (326) | main | Sent 1 ATTRIB requests
2016-11-03 21:37:05,673 | INFO     | looper.py            (253) | shutdown | Looper shutting down now...
2016-11-03 21:37:05,684 | DEBUG    | motor.py             (34) | set_status | Claaaa6 changing status from started_hungry to stopping
2016-11-03 21:37:05,684 | INFO     | stacked.py           (82) | stop | stack Claaaa6 stopped
2016-11-03 21:37:05,684 | DEBUG    | motor.py             (34) | set_status | Claaaa6 changing status from stopping to stopped
2016-11-03 21:37:05,684 | INFO     | looper.py            (260) | shutdown | Looper shut down in 0.011 seconds.
2016-11-03 21:37:05,730 | DEBUG    | base_events.py       (410) | close | Close <_UnixSelectorEventLoop running=False closed=False debug=True>
