2016-11-03 21:36:43,463 | INFO     | log.py               (128) | setupLogging | Choosing RAET log level 1
2016-11-03 21:36:46,131 | DEBUG    | testable.py          (126) | decorator | in SpyableTestClient added spy on __init__
2016-11-03 21:36:46,131 | WARNING  | testable.py          (134) | decorator | method <function Client.handleOneNodeMsg at 0x7fd851049ea0> not found, so no spy added
2016-11-03 21:36:46,168 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on __init__
2016-11-03 21:36:46,168 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterReqLatencyTooHigh
2016-11-03 21:36:46,168 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterThroughputTooLow
2016-11-03 21:36:46,169 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on sendThroughput
2016-11-03 21:36:46,174 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on __init__
2016-11-03 21:36:46,174 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on catchupCompleted
2016-11-03 21:36:46,174 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on processConsistencyProofReq
2016-11-03 21:36:46,174 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on startCatchUpProcess
2016-11-03 21:36:46,177 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on __init__
2016-11-03 21:36:46,177 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on addToPrePrepares
2016-11-03 21:36:46,177 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canProcessPrePrepare
2016-11-03 21:36:46,178 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canSendPrepare
2016-11-03 21:36:46,178 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doOrder
2016-11-03 21:36:46,178 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrePrepare
2016-11-03 21:36:46,178 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrepare
2016-11-03 21:36:46,178 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on isValidPrepare
2016-11-03 21:36:46,178 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on orderPendingCommit
2016-11-03 21:36:46,178 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processCommit
2016-11-03 21:36:46,178 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrePrepare
2016-11-03 21:36:46,178 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrepare
2016-11-03 21:36:46,182 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on __init__
2016-11-03 21:36:46,182 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on checkPerformance
2016-11-03 21:36:46,182 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on decidePrimaries
2016-11-03 21:36:46,182 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on discard
2016-11-03 21:36:46,183 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on eatTestMsg
2016-11-03 21:36:46,183 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on forward
2016-11-03 21:36:46,183 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleInvalidClientMsg
2016-11-03 21:36:46,183 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleOneNodeMsg
2016-11-03 21:36:46,207 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToClientInBox
2016-11-03 21:36:46,207 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToNodeInBox
2016-11-03 21:36:46,207 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processInstanceChange
2016-11-03 21:36:46,208 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processOrdered
2016-11-03 21:36:46,208 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processPropagate
2016-11-03 21:36:46,208 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processRequest
2016-11-03 21:36:46,208 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on propagate
2016-11-03 21:36:46,208 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousClient
2016-11-03 21:36:46,208 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousNode
2016-11-03 21:36:46,208 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on send
2016-11-03 21:36:46,208 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on sendInstanceChange
2016-11-03 21:36:46,208 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on startViewChange
Loading module /home/lovesh/.virtualenvs/sovrin-dev/lib/python3.5/site-packages/anoncreds_dev-0.1.8-py3.5.egg/config/config-crypto-example1.py
Module loaded.
2016-11-03 21:36:46,842 | DEBUG    | gen_load_ratcheting  (280) | main | Results file: /home/lovesh/dev/evernym/sovrin-priv/scripts/perf_results_1_2_1478189206.csv
2016-11-03 21:36:46,842 | INFO     | gen_load_ratcheting  (136) | _spawnClient | Seed for client Claaaa8 is b'0000000000000000000000000Claaaa8', its len is 32
2016-11-03 21:36:46,851 | DEBUG    | ledger.py            (164) | start | Starting ledger...
2016-11-03 21:36:46,851 | DEBUG    | ledger.py            (69) | recoverTree | Recovering tree from transaction log
2016-11-03 21:36:46,892 | INFO     | client.py            (121) | __init__ | Client Claaaa8 initialized with the following node registry:
2016-11-03 21:36:46,893 | INFO     | client.py            (128) | __init__ |     EvernymV1C      listens at 52.33.22.91    on port 9722
2016-11-03 21:36:46,893 | INFO     | client.py            (128) | __init__ |     EvernymV2C      listens at 52.38.24.189   on port 9724
2016-11-03 21:36:46,893 | INFO     | client.py            (128) | __init__ |     WSECUC          listens at 13.93.218.255  on port 9726
2016-11-03 21:36:46,893 | INFO     | client.py            (128) | __init__ |     BIGC            listens at 52.160.103.164 on port 9728
2016-11-03 21:36:46,893 | INFO     | client.py            (128) | __init__ |     RespectNetworkC listens at 54.173.9.185   on port 9730
2016-11-03 21:36:46,893 | INFO     | client.py            (128) | __init__ |     FCUC            listens at 69.144.146.171 on port 9734
2016-11-03 21:36:46,893 | INFO     | client.py            (128) | __init__ |     BYUC            listens at 54.193.6.155   on port 9745
2016-11-03 21:36:46,893 | DEBUG    | plugin_helper.py     (25) | loadPlugins | Plugin loading started to load plugins from basedir: /home/lovesh/.sovrin
2016-11-03 21:36:47,340 | DEBUG    | plugin_helper.py     (68) | loadPlugins | Total plugins loaded from basedir /home/lovesh/.sovrin are : 1
2016-11-03 21:36:47,340 | DEBUG    | client.py            (148) | __init__ | total plugins loaded in client: 1
2016-11-03 21:36:47,340 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
2016-11-03 21:36:47,340 | DEBUG    | looper.py            (121) | __init__ | Setting handler for SIGINT
2016-11-03 21:36:47,341 | DEBUG    | motor.py             (34) | set_status | Claaaa8 changing status from stopped to starting
2016-11-03 21:36:47,341 | INFO     | stacked.py           (75) | start | stack Claaaa8 starting at ('0.0.0.0', 5936) in always mode
2016-11-03 21:36:47,341 | INFO     | stacked.py           (851) | start | Claaaa8 listening for other nodes at 0.0.0.0:5936
2016-11-03 21:36:47,341 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa8 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:47,341 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa8 nodestack is []
2016-11-03 21:36:47,341 | DEBUG    | stacked.py           (504) | connectToMissing | Claaaa8 found the following missing connections: RespectNetworkC, WSECUC, FCUC, BIGC, BYUC, EvernymV1C, EvernymV2C
2016-11-03 21:36:47,396 | INFO     | stacked.py           (456) | connect | Claaaa8 looking for RespectNetworkC at 54.173.9.185:9730
2016-11-03 21:36:47,523 | INFO     | stacked.py           (456) | connect | Claaaa8 looking for WSECUC at 13.93.218.255:9726
2016-11-03 21:36:47,961 | INFO     | stacked.py           (456) | connect | Claaaa8 looking for FCUC at 69.144.146.171:9734
2016-11-03 21:36:48,012 | INFO     | stacked.py           (456) | connect | Claaaa8 looking for BIGC at 52.160.103.164:9728
2016-11-03 21:36:48,032 | INFO     | stacked.py           (456) | connect | Claaaa8 looking for BYUC at 54.193.6.155:9745
2016-11-03 21:36:48,050 | INFO     | stacked.py           (456) | connect | Claaaa8 looking for EvernymV1C at 52.33.22.91:9722
2016-11-03 21:36:48,068 | INFO     | stacked.py           (456) | connect | Claaaa8 looking for EvernymV2C at 52.38.24.189:9724
2016-11-03 21:36:48,069 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa8 next check for retries in 6.00 seconds
2016-11-03 21:36:48,073 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Staler 'Claaaa8'. Stale transaction '1' packet 'None' from '('54.173.9.185', 9730)' in 1 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '0'
Staler 'Claaaa8'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 1 at 1.5527630069991574
2016-11-03 21:36:48,451 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Staler 'Claaaa8'. Stale transaction '1' packet 'None' from '('52.38.24.189', 9724)' in 1 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '0'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 1 at 1.5692941599991173
Staler 'Claaaa8'. Stale transaction '1' packet 'None' from '('52.33.22.91', 9722)' in 1 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '0'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 1 at 1.5865844669970102
Staler 'Claaaa8'. Stale transaction '1' packet 'None' from '('54.193.6.155', 9745)' in 1 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '0'
Staler 'Claaaa8'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 1 at 1.6369274120006594
Staler 'Claaaa8'. Stale transaction '1' packet 'None' from '('52.33.22.91', 9722)' in 1 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '0'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 1 at 1.8066708379992633
2016-11-03 21:36:48,826 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 21:36:48,939 | DEBUG    | stacked.py           (294) | conns | Claaaa8's connection changed from set() to {'BYUC'}
2016-11-03 21:36:48,939 | INFO     | stacked.py           (320) | _connsChanged | Claaaa8 now connected to BYUC
2016-11-03 21:36:48,940 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa8 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BYUC
2016-11-03 21:36:48,962 | DEBUG    | stacked.py           (294) | conns | Claaaa8's connection changed from {'BYUC'} to {'RespectNetworkC', 'BYUC'}
2016-11-03 21:36:48,962 | INFO     | stacked.py           (320) | _connsChanged | Claaaa8 now connected to RespectNetworkC
2016-11-03 21:36:48,962 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa8 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to RespectNetworkC
Staler 'Claaaa8'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '0'
Staler 'Claaaa8'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.1433660019974923
2016-11-03 21:36:49,086 | DEBUG    | stacked.py           (294) | conns | Claaaa8's connection changed from {'RespectNetworkC', 'BYUC'} to {'RespectNetworkC', 'BYUC', 'EvernymV1C', 'EvernymV2C'}
2016-11-03 21:36:49,086 | INFO     | stacked.py           (320) | _connsChanged | Claaaa8 now connected to EvernymV1C
2016-11-03 21:36:49,086 | INFO     | stacked.py           (320) | _connsChanged | Claaaa8 now connected to EvernymV2C
2016-11-03 21:36:49,086 | DEBUG    | motor.py             (34) | set_status | Claaaa8 changing status from starting to started_hungry
2016-11-03 21:36:49,087 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa8 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV2C
2016-11-03 21:36:49,087 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa8 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV1C
2016-11-03 21:36:49,204 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 4 / 7 nodes
Staler 'Claaaa8'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '0'
Staler 'Claaaa8'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.3494615980016533
2016-11-03 21:36:49,317 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa8 got msg from node RespectNetworkC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,317 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa8 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from RespectNetworkC
2016-11-03 21:36:49,317 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa8 cannot start catchup since received only 1 consistency proofs but need at least 3
2016-11-03 21:36:49,346 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa8 got msg from node BYUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,346 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa8 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BYUC
2016-11-03 21:36:49,346 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa8 scheduling action functools.partial(<bound method LedgerManager.checkIfCPsNeeded of Claaaa8>, 0) with id 1 to run in 30 seconds
2016-11-03 21:36:49,347 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa8 cannot start catchup since received only 2 consistency proofs but need at least 3
Staler 'Claaaa8'. Stale transaction '3' packet '1' from '('52.38.24.189', 9724)' in 2 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '488'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 2 at 2.5296556819957914
Staler 'Claaaa8'. Stale transaction '4' packet '1' from '('54.193.6.155', 9745)' in 3 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '440'
Staler 'Claaaa8'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 3 at 2.55915550699865
Staler 'Claaaa8'. Stale transaction '3' packet '1' from '('52.33.22.91', 9722)' in 2 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '472'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 2 at 2.5848662439966574
Staler 'Claaaa8'. Stale transaction '4' packet '1' from '('54.173.9.185', 9730)' in 3 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '479'
Staler 'Claaaa8'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 3 at 2.5848662439966574
2016-11-03 21:36:49,585 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 4 / 7 nodes
Staler 'Claaaa8'. Stale transaction '4' packet '1' from '('52.33.22.91', 9722)' in 3 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '472'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 3 at 2.7735987810010556
2016-11-03 21:36:49,674 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa8 got msg from node EvernymV1C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,675 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa8 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV1C
2016-11-03 21:36:49,675 | DEBUG    | ledger_manager.py    (576) | canStartCatchUpProcess | Claaaa8 deciding on the basis of CPs {'RespectNetworkC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'BYUC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'EvernymV1C': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='])} and f 1
2016-11-03 21:36:49,675 | DEBUG    | ledger_manager.py    (656) | startCatchUpProcess | Claaaa8 started catching up with consistency proof CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=('Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='))
2016-11-03 21:36:49,675 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa8 scheduling action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa8>, 0) with id 2 to run in 5.1 seconds
2016-11-03 21:36:49,676 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa8 sending msg OrderedDict([('op', 'CATCHUP_REQ'), ('ledgerType', 0), ('seqNoStart', 8), ('seqNoEnd', 8)]) to RespectNetworkC
2016-11-03 21:36:49,689 | DEBUG    | stacked.py           (294) | conns | Claaaa8's connection changed from {'RespectNetworkC', 'BYUC', 'EvernymV1C', 'EvernymV2C'} to {'RespectNetworkC', 'BYUC', 'EvernymV1C', 'FCUC', 'EvernymV2C'}
2016-11-03 21:36:49,690 | INFO     | stacked.py           (320) | _connsChanged | Claaaa8 now connected to FCUC
2016-11-03 21:36:49,690 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa8 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to FCUC
Staler 'Claaaa8'. Stale transaction '4' packet '1' from '('52.38.24.189', 9724)' in 3 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '488'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 3 at 2.838378581996949
2016-11-03 21:36:49,748 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa8 got msg from node EvernymV2C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,748 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa8 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV2C
2016-11-03 21:36:49,748 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa8 cannot process consistency proof since in state 2 and canSync is True
Staler 'Claaaa8'. Stale transaction '3' packet '1' from '('69.144.146.171', 9734)' in 2 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '341'
Staler 'Claaaa8'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 2 at 3.016748114998336
2016-11-03 21:36:49,944 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa8 got msg from node RespectNetworkC: {'op': 'CATCHUP_REP', 'ledgerType': 0, 'txns': {'8': {'txnTime': 1478157003369.697, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'reqId': 1478156921805694, 'data': {'node_ip': '40.121.149.41', 'node_port': 9725, 'alias': 'WSECU', 'client_ip': '40.121.149.41', 'client_port': 9726}, 'type': 'CHANGE_HA', 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b'}}, 'consProof': []}
2016-11-03 21:36:49,945 | DEBUG    | ledger_manager.py    (384) | processCatchupRep | Claaaa8 received catchup reply from RespectNetworkC: CATCHUP_REP(ledgerType=0, txns={'8': {'txnTime': 1478157003369.697, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'reqId': 1478156921805694, 'data': {'node_ip': '40.121.149.41', 'node_port': 9725, 'alias': 'WSECU', 'client_ip': '40.121.149.41', 'client_port': 9726}, 'type': 'CHANGE_HA', 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b'}}, consProof=[])
2016-11-03 21:36:49,945 | DEBUG    | ledger_manager.py    (390) | processCatchupRep | Claaaa8 found 1 transactions in the catchup from RespectNetworkC
2016-11-03 21:36:49,945 | DEBUG    | ledger_manager.py    (399) | processCatchupRep | Claaaa8 merging all received catchups
2016-11-03 21:36:49,945 | DEBUG    | ledger_manager.py    (405) | processCatchupRep | Claaaa8 merged catchups, there are 1 of them now, from 8 to 8
2016-11-03 21:36:49,945 | DEBUG    | ledger_manager.py    (496) | hasValidCatchupReplies | Claaaa8 verifying proof for 8, 8, b'\xc8v\xe37\xc5\xb5\xf0S\x827m\x9d\xe9\xbf\x8b\xc9\xc4\xd7\xaf)\x0b\xb5\xfa\x06\x90\xb1Ed\xb8\xb9ya', b'\xd7\x99p\xfar\xf5\xd9\x9e\xb8\xd2\x05\xe3\x81\x9f\x8c\xdd2;\xfd\xab(\xf6\xbcU\tNW\xc0jDMV', []
2016-11-03 21:36:49,945 | INFO     | ledger_manager.py    (505) | hasValidCatchupReplies | Claaaa8 could not verify catchup reply CATCHUP_REP(ledgerType=0, txns={'8': {'txnTime': 1478157003369.697, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'reqId': 1478156921805694, 'data': {'node_ip': '40.121.149.41', 'node_port': 9725, 'alias': 'WSECU', 'client_ip': '40.121.149.41', 'client_port': 9726}, 'type': 'CHANGE_HA', 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b'}}, consProof=[]) since Inconsistency: different root hashes for the same tree size
2016-11-03 21:36:49,945 | DEBUG    | ledger_manager.py    (413) | processCatchupRep | Claaaa8 processed 0 catchup replies with sequence numbers []
2016-11-03 21:36:49,961 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:50,021 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa8 got msg from node FCUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:50,021 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa8 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from FCUC
2016-11-03 21:36:50,021 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa8 cannot process consistency proof since in state 2 and canSync is True
Staler 'Claaaa8'. Stale transaction '4' packet '1' from '('69.144.146.171', 9734)' in 3 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '341'
Staler 'Claaaa8'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 3 at 3.3363723529982963
2016-11-03 21:36:50,338 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:50,715 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,092 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,469 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,845 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa8'. Stale transaction '1' packet 'None' from '('52.160.103.164', 9728)' in 1 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '0'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 1 at 5.323532686998078
2016-11-03 21:36:52,226 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,603 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,982 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,344 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa8 join already in process, so waiting to check for reconnects
2016-11-03 21:36:53,345 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Claaaa8 allow already in process, so waiting to check for reconnects
2016-11-03 21:36:53,345 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa8 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:53,345 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa8 nodestack is ['RespectNetworkC', 'estate_85a62483a1df11e6ac2c6807152028e4', 'FCUC', 'BIGC', 'BYUC', 'EvernymV1C', 'EvernymV2C']
2016-11-03 21:36:53,345 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 2 ('54.173.9.185', 9730)
2016-11-03 21:36:53,345 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa8 unmatched remote is 3 ('13.93.218.255', 9726)
2016-11-03 21:36:53,345 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa8 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_85a62483a1df11e6ac2c6807152028e4
2016-11-03 21:36:53,345 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 4 ('69.144.146.171', 9734)
2016-11-03 21:36:53,346 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 5 ('52.160.103.164', 9728)
2016-11-03 21:36:53,346 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 6 ('54.193.6.155', 9745)
2016-11-03 21:36:53,346 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 7 ('52.33.22.91', 9722)
2016-11-03 21:36:53,346 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 8 ('52.38.24.189', 9724)
2016-11-03 21:36:53,346 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa8 next check for retries in 6.00 seconds
2016-11-03 21:36:53,358 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,736 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,112 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,489 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,784 | DEBUG    | has_action_queue.py  (60) | _serviceActions | Claaaa8 running action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa8>, 0) with id 2
2016-11-03 21:36:54,866 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:55,242 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:55,500 | DEBUG    | stacked.py           (294) | conns | Claaaa8's connection changed from {'RespectNetworkC', 'BYUC', 'EvernymV1C', 'FCUC', 'EvernymV2C'} to {'RespectNetworkC', 'BIGC', 'EvernymV2C', 'FCUC', 'BYUC', 'EvernymV1C'}
2016-11-03 21:36:55,500 | INFO     | stacked.py           (320) | _connsChanged | Claaaa8 now connected to BIGC
2016-11-03 21:36:55,500 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa8 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BIGC
2016-11-03 21:36:55,619 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 6 / 7 nodes
2016-11-03 21:36:55,619 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkIfConnectedToAll) succeeded with -0.05 seconds to spare
2016-11-03 21:36:55,621 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'reqId': 1478189215620770, 'signature': None, 'identifier': '9XeZpmy2r5VevD1BDDDjxygbwx8xHxPtbPcruKi2cms1', 'operation': {'type': 'ATTRIB', 'raw': '69922c18f27b0e4058ec1f6a73552c9b6ea3dabfb0e55fc0323875df6fd2aac2'}} into identifier:9XeZpmy2r5VevD1BDDDjxygbwx8xHxPtbPcruKi2cms1|operation:raw:69922c18f27b0e4058ec1f6a73552c9b6ea3dabfb0e55fc0323875df6fd2aac2|type:ATTRIB|reqId:1478189215620770
2016-11-03 21:36:55,621 | DEBUG    | client.py            (228) | submitReqs | Claaaa8 pending request since in mode 1 and connected to {'RespectNetworkC', 'BIGC', 'EvernymV2C', 'FCUC', 'BYUC', 'EvernymV1C'} nodes
2016-11-03 21:36:55,622 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'operation': {'raw': '{"avZKXPQj3CrHzg6U4opc_731024": "741419300844_LOMvr064Ryim78hYDgbwPqSxCtNBjEcaH5Qd2nk31ouAUFzGTp"}', 'type': 'ATTRIB'}, 'reqId': 1478189215620770, 'signature': '865s6FqeR5BJxTC9AdaKniDXzPHGrJbEXuCmYYr9dQuoJ5YTDY8dHCd7Rqni2dR9TKPh2Y8uHrVLoeKTvhs7sfT', 'identifier': '9XeZpmy2r5VevD1BDDDjxygbwx8xHxPtbPcruKi2cms1'}
2016-11-03 21:36:55,622 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa8 sending request Request: {'operation': {'raw': '{"avZKXPQj3CrHzg6U4opc_731024": "741419300844_LOMvr064Ryim78hYDgbwPqSxCtNBjEcaH5Qd2nk31ouAUFzGTp"}', 'type': 'ATTRIB'}, 'reqId': 1478189215620770, 'signature': '865s6FqeR5BJxTC9AdaKniDXzPHGrJbEXuCmYYr9dQuoJ5YTDY8dHCd7Rqni2dR9TKPh2Y8uHrVLoeKTvhs7sfT', 'identifier': '9XeZpmy2r5VevD1BDDDjxygbwx8xHxPtbPcruKi2cms1'}
Staler 'Claaaa8'. Stale transaction '3' packet '1' from '('52.160.103.164', 9728)' in 2 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '481'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 2 at 10.649009635002585
2016-11-03 21:36:59,355 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa8 join already in process, so waiting to check for reconnects
2016-11-03 21:36:59,356 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa8 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:59,356 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa8 nodestack is ['RespectNetworkC', 'estate_85a62483a1df11e6ac2c6807152028e4', 'FCUC', 'BIGC', 'BYUC', 'EvernymV1C', 'EvernymV2C']
2016-11-03 21:36:59,356 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 2 ('54.173.9.185', 9730)
2016-11-03 21:36:59,356 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa8 unmatched remote is 3 ('13.93.218.255', 9726)
2016-11-03 21:36:59,356 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa8 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_85a62483a1df11e6ac2c6807152028e4
2016-11-03 21:36:59,356 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 4 ('69.144.146.171', 9734)
2016-11-03 21:36:59,356 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 5 ('52.160.103.164', 9728)
2016-11-03 21:36:59,356 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 6 ('54.193.6.155', 9745)
2016-11-03 21:36:59,357 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 7 ('52.33.22.91', 9722)
2016-11-03 21:36:59,357 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 8 ('52.38.24.189', 9724)
2016-11-03 21:36:59,357 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa8 next check for retries in 6.00 seconds
Staler 'Claaaa8'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '481'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.421951008000178
Staler 'Claaaa8'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '481'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.421951008000178
Staler 'Claaaa8'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '481'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.421951008000178
2016-11-03 21:37:00,658 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa8', signerId='9XeZpmy2r5VevD1BDDDjxygbwx8xHxPtbPcruKi2cms1', reqId=1478189215620770, transactionType='ATTRIB', sentAt=1478189215.6219296, quorumAt='', latency=5.036508083343506, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:37:00,659 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.46 seconds to spare
2016-11-03 21:37:00,659 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 5.039481163024902
        Average latency: 5.036508083343506
        Throughput: 0.0
        Error rate: 0.19843312588150624
        Succeeded: 0
        Failed: 1
        Query Time: 0
        ================================
        
2016-11-03 21:37:00,660 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'reqId': 1478189220660050, 'signature': None, 'identifier': '9XeZpmy2r5VevD1BDDDjxygbwx8xHxPtbPcruKi2cms1', 'operation': {'type': 'ATTRIB', 'raw': 'ee71a8f5a694bd732c60463ac6c63f2c9d4b2c7ffb174abe0f4979a9b6f1fdfb'}} into identifier:9XeZpmy2r5VevD1BDDDjxygbwx8xHxPtbPcruKi2cms1|operation:raw:ee71a8f5a694bd732c60463ac6c63f2c9d4b2c7ffb174abe0f4979a9b6f1fdfb|type:ATTRIB|reqId:1478189220660050
2016-11-03 21:37:00,660 | DEBUG    | client.py            (228) | submitReqs | Claaaa8 pending request since in mode 1 and connected to {'RespectNetworkC', 'BIGC', 'EvernymV2C', 'FCUC', 'BYUC', 'EvernymV1C'} nodes
2016-11-03 21:37:00,661 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'operation': {'raw': '{"KElrdWbyxAYQNTBM1IwP_704552": "89769900653_eWHXF9VEBO7MpPTtQ2YSh3AjgIRi8zbNJcovUdqs1ZlDK0mkC5"}', 'type': 'ATTRIB'}, 'reqId': 1478189220660050, 'signature': '26C2ocqNVmHeigQJBaDGGyFh3yM2GvqQPLLH6oLo2RZoejG9g3mgwW9svChLY2te5X2YSRkTQ7U3Jn2dWn2D8rkm', 'identifier': '9XeZpmy2r5VevD1BDDDjxygbwx8xHxPtbPcruKi2cms1'}
2016-11-03 21:37:00,661 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa8 sending request Request: {'operation': {'raw': '{"KElrdWbyxAYQNTBM1IwP_704552": "89769900653_eWHXF9VEBO7MpPTtQ2YSh3AjgIRi8zbNJcovUdqs1ZlDK0mkC5"}', 'type': 'ATTRIB'}, 'reqId': 1478189220660050, 'signature': '26C2ocqNVmHeigQJBaDGGyFh3yM2GvqQPLLH6oLo2RZoejG9g3mgwW9svChLY2te5X2YSRkTQ7U3Jn2dWn2D8rkm', 'identifier': '9XeZpmy2r5VevD1BDDDjxygbwx8xHxPtbPcruKi2cms1'}
Staler 'Claaaa8'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '481'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 14.624288156999683
Staler 'Claaaa8'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '481'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 14.624288156999683
2016-11-03 21:37:01,537 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa8 got msg from node BIGC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:37:01,537 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa8 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BIGC
2016-11-03 21:37:01,537 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa8 cannot process consistency proof since in state 2 and canSync is True
Staler 'Claaaa8'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa8'. Unknown correspondent estate id '481'
Staler 'Claaaa8'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 15.195656953997968
Stalent 'Claaaa8'. Stale transaction '0' packet '0' from '('52.160.103.164', 9728)' in 1 nacking ...
Stalent 'Claaaa8'. Unknown initiator estate id '481'
Stalent 'Claaaa8'. Do Nack of ('52.160.103.164', 9728) in 1 at 15.195656953997968
2016-11-03 21:37:05,358 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa8 join already in process, so waiting to check for reconnects
2016-11-03 21:37:05,358 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa8 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:37:05,358 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa8 nodestack is ['RespectNetworkC', 'estate_85a62483a1df11e6ac2c6807152028e4', 'FCUC', 'BIGC', 'BYUC', 'EvernymV1C', 'EvernymV2C']
2016-11-03 21:37:05,359 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 2 ('54.173.9.185', 9730)
2016-11-03 21:37:05,359 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa8 unmatched remote is 3 ('13.93.218.255', 9726)
2016-11-03 21:37:05,359 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa8 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_85a62483a1df11e6ac2c6807152028e4
2016-11-03 21:37:05,359 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 4 ('69.144.146.171', 9734)
2016-11-03 21:37:05,359 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 5 ('52.160.103.164', 9728)
2016-11-03 21:37:05,359 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 6 ('54.193.6.155', 9745)
2016-11-03 21:37:05,359 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 7 ('52.33.22.91', 9722)
2016-11-03 21:37:05,359 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa8 matched remote is 8 ('52.38.24.189', 9724)
2016-11-03 21:37:05,359 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa8 next check for retries in 6.00 seconds
2016-11-03 21:37:05,701 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa8', signerId='9XeZpmy2r5VevD1BDDDjxygbwx8xHxPtbPcruKi2cms1', reqId=1478189220660050, transactionType='ATTRIB', sentAt=1478189220.6607509, quorumAt='', latency=5.040231704711914, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:37:05,701 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.46 seconds to spare
2016-11-03 21:37:05,701 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 10.081418991088867
        Average latency: 5.03836989402771
        Throughput: 0.0
        Error rate: 0.1983847712080842
        Succeeded: 0
        Failed: 2
        Query Time: 0
        ================================
        
2016-11-03 21:37:05,701 | DEBUG    | gen_load_ratcheting  (326) | main | Sent 1 ATTRIB requests
2016-11-03 21:37:05,701 | INFO     | looper.py            (253) | shutdown | Looper shutting down now...
2016-11-03 21:37:05,706 | DEBUG    | motor.py             (34) | set_status | Claaaa8 changing status from started_hungry to stopping
2016-11-03 21:37:05,706 | INFO     | stacked.py           (82) | stop | stack Claaaa8 stopped
2016-11-03 21:37:05,707 | DEBUG    | motor.py             (34) | set_status | Claaaa8 changing status from stopping to stopped
2016-11-03 21:37:05,707 | INFO     | looper.py            (260) | shutdown | Looper shut down in 0.005 seconds.
2016-11-03 21:37:05,750 | DEBUG    | base_events.py       (410) | close | Close <_UnixSelectorEventLoop running=False closed=False debug=True>
