2016-11-03 21:36:43,495 | INFO     | log.py               (128) | setupLogging | Choosing RAET log level 1
2016-11-03 21:36:45,815 | DEBUG    | testable.py          (126) | decorator | in SpyableTestClient added spy on __init__
2016-11-03 21:36:45,816 | WARNING  | testable.py          (134) | decorator | method <function Client.handleOneNodeMsg at 0x7f6400ed7ea0> not found, so no spy added
2016-11-03 21:36:45,837 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on __init__
2016-11-03 21:36:45,837 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterReqLatencyTooHigh
2016-11-03 21:36:45,837 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterThroughputTooLow
2016-11-03 21:36:45,837 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on sendThroughput
2016-11-03 21:36:45,840 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on __init__
2016-11-03 21:36:45,840 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on catchupCompleted
2016-11-03 21:36:45,840 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on processConsistencyProofReq
2016-11-03 21:36:45,840 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on startCatchUpProcess
2016-11-03 21:36:45,857 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on __init__
2016-11-03 21:36:45,857 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on addToPrePrepares
2016-11-03 21:36:45,857 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canProcessPrePrepare
2016-11-03 21:36:45,858 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canSendPrepare
2016-11-03 21:36:45,858 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doOrder
2016-11-03 21:36:45,858 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrePrepare
2016-11-03 21:36:45,858 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrepare
2016-11-03 21:36:45,858 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on isValidPrepare
2016-11-03 21:36:45,858 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on orderPendingCommit
2016-11-03 21:36:45,858 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processCommit
2016-11-03 21:36:45,858 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrePrepare
2016-11-03 21:36:45,858 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrepare
2016-11-03 21:36:45,862 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on __init__
2016-11-03 21:36:45,862 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on checkPerformance
2016-11-03 21:36:45,862 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on decidePrimaries
2016-11-03 21:36:45,863 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on discard
2016-11-03 21:36:45,863 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on eatTestMsg
2016-11-03 21:36:45,863 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on forward
2016-11-03 21:36:45,863 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleInvalidClientMsg
2016-11-03 21:36:45,863 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleOneNodeMsg
2016-11-03 21:36:45,863 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToClientInBox
2016-11-03 21:36:45,863 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToNodeInBox
2016-11-03 21:36:45,863 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processInstanceChange
2016-11-03 21:36:45,864 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processOrdered
2016-11-03 21:36:45,864 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processPropagate
2016-11-03 21:36:45,864 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processRequest
2016-11-03 21:36:45,864 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on propagate
2016-11-03 21:36:45,864 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousClient
2016-11-03 21:36:45,864 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousNode
2016-11-03 21:36:45,864 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on send
2016-11-03 21:36:45,864 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on sendInstanceChange
2016-11-03 21:36:45,864 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on startViewChange
Loading module /home/lovesh/.virtualenvs/sovrin-dev/lib/python3.5/site-packages/anoncreds_dev-0.1.8-py3.5.egg/config/config-crypto-example1.py
Module loaded.
2016-11-03 21:36:46,481 | DEBUG    | gen_load_ratcheting  (280) | main | Results file: /home/lovesh/dev/evernym/sovrin-priv/scripts/perf_results_1_2_1478189206.csv
2016-11-03 21:36:46,481 | INFO     | gen_load_ratcheting  (136) | _spawnClient | Seed for client Claaaa9 is b'0000000000000000000000000Claaaa9', its len is 32
2016-11-03 21:36:46,482 | DEBUG    | ledger.py            (164) | start | Starting ledger...
2016-11-03 21:36:46,483 | DEBUG    | ledger.py            (69) | recoverTree | Recovering tree from transaction log
2016-11-03 21:36:46,515 | INFO     | client.py            (121) | __init__ | Client Claaaa9 initialized with the following node registry:
2016-11-03 21:36:46,515 | INFO     | client.py            (128) | __init__ |     EvernymV1C      listens at 52.33.22.91    on port 9722
2016-11-03 21:36:46,515 | INFO     | client.py            (128) | __init__ |     EvernymV2C      listens at 52.38.24.189   on port 9724
2016-11-03 21:36:46,516 | INFO     | client.py            (128) | __init__ |     WSECUC          listens at 13.93.218.255  on port 9726
2016-11-03 21:36:46,516 | INFO     | client.py            (128) | __init__ |     BIGC            listens at 52.160.103.164 on port 9728
2016-11-03 21:36:46,516 | INFO     | client.py            (128) | __init__ |     RespectNetworkC listens at 54.173.9.185   on port 9730
2016-11-03 21:36:46,516 | INFO     | client.py            (128) | __init__ |     FCUC            listens at 69.144.146.171 on port 9734
2016-11-03 21:36:46,516 | INFO     | client.py            (128) | __init__ |     BYUC            listens at 54.193.6.155   on port 9745
2016-11-03 21:36:46,516 | DEBUG    | plugin_helper.py     (25) | loadPlugins | Plugin loading started to load plugins from basedir: /home/lovesh/.sovrin
2016-11-03 21:36:47,251 | DEBUG    | plugin_helper.py     (68) | loadPlugins | Total plugins loaded from basedir /home/lovesh/.sovrin are : 1
2016-11-03 21:36:47,251 | DEBUG    | client.py            (148) | __init__ | total plugins loaded in client: 1
2016-11-03 21:36:47,251 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
2016-11-03 21:36:47,252 | DEBUG    | looper.py            (121) | __init__ | Setting handler for SIGINT
2016-11-03 21:36:47,252 | DEBUG    | motor.py             (34) | set_status | Claaaa9 changing status from stopped to starting
2016-11-03 21:36:47,252 | INFO     | stacked.py           (75) | start | stack Claaaa9 starting at ('0.0.0.0', 6488) in always mode
2016-11-03 21:36:47,252 | INFO     | stacked.py           (851) | start | Claaaa9 listening for other nodes at 0.0.0.0:6488
2016-11-03 21:36:47,252 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa9 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:47,252 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa9 nodestack is []
2016-11-03 21:36:47,252 | DEBUG    | stacked.py           (504) | connectToMissing | Claaaa9 found the following missing connections: BYUC, EvernymV1C, RespectNetworkC, FCUC, EvernymV2C, WSECUC, BIGC
2016-11-03 21:36:47,308 | INFO     | stacked.py           (456) | connect | Claaaa9 looking for BYUC at 54.193.6.155:9745
2016-11-03 21:36:47,360 | INFO     | stacked.py           (456) | connect | Claaaa9 looking for EvernymV1C at 52.33.22.91:9722
2016-11-03 21:36:47,415 | INFO     | stacked.py           (456) | connect | Claaaa9 looking for RespectNetworkC at 54.173.9.185:9730
2016-11-03 21:36:47,666 | INFO     | stacked.py           (456) | connect | Claaaa9 looking for FCUC at 69.144.146.171:9734
2016-11-03 21:36:47,719 | INFO     | stacked.py           (456) | connect | Claaaa9 looking for EvernymV2C at 52.38.24.189:9724
2016-11-03 21:36:47,739 | INFO     | stacked.py           (456) | connect | Claaaa9 looking for WSECUC at 13.93.218.255:9726
2016-11-03 21:36:47,761 | INFO     | stacked.py           (456) | connect | Claaaa9 looking for BIGC at 52.160.103.164:9728
2016-11-03 21:36:47,761 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa9 next check for retries in 6.00 seconds
2016-11-03 21:36:47,767 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 21:36:48,161 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Staler 'Claaaa9'. Stale transaction '1' packet 'None' from '('54.193.6.155', 9745)' in 1 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '0'
Staler 'Claaaa9'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 1 at 1.6878171790012857
Staler 'Claaaa9'. Stale transaction '1' packet 'None' from '('54.173.9.185', 9730)' in 1 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '0'
Staler 'Claaaa9'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 1 at 1.750176650006324
Staler 'Claaaa9'. Stale transaction '1' packet 'None' from '('52.33.22.91', 9722)' in 1 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '0'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 1 at 1.750176650006324
Staler 'Claaaa9'. Stale transaction '1' packet 'None' from '('52.38.24.189', 9724)' in 1 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '0'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 1 at 1.750176650006324
Staler 'Claaaa9'. Stale transaction '1' packet 'None' from '('52.33.22.91', 9722)' in 1 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '0'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 1 at 1.9497088250063825
Staler 'Claaaa9'. Stale transaction '1' packet 'None' from '('52.38.24.189', 9724)' in 1 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '0'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 1 at 1.9697729870022158
2016-11-03 21:36:48,537 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 21:36:48,785 | DEBUG    | stacked.py           (294) | conns | Claaaa9's connection changed from set() to {'RespectNetworkC'}
2016-11-03 21:36:48,785 | INFO     | stacked.py           (320) | _connsChanged | Claaaa9 now connected to RespectNetworkC
2016-11-03 21:36:48,786 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa9 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to RespectNetworkC
2016-11-03 21:36:48,822 | DEBUG    | stacked.py           (294) | conns | Claaaa9's connection changed from {'RespectNetworkC'} to {'BYUC', 'RespectNetworkC'}
2016-11-03 21:36:48,822 | INFO     | stacked.py           (320) | _connsChanged | Claaaa9 now connected to BYUC
2016-11-03 21:36:48,822 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa9 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BYUC
2016-11-03 21:36:48,917 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 2 / 7 nodes
2016-11-03 21:36:48,955 | DEBUG    | stacked.py           (294) | conns | Claaaa9's connection changed from {'BYUC', 'RespectNetworkC'} to {'BYUC', 'EvernymV1C', 'RespectNetworkC'}
2016-11-03 21:36:48,955 | INFO     | stacked.py           (320) | _connsChanged | Claaaa9 now connected to EvernymV1C
2016-11-03 21:36:48,955 | DEBUG    | motor.py             (34) | set_status | Claaaa9 changing status from starting to started_hungry
2016-11-03 21:36:48,955 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa9 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV1C
2016-11-03 21:36:48,982 | DEBUG    | stacked.py           (294) | conns | Claaaa9's connection changed from {'BYUC', 'EvernymV1C', 'RespectNetworkC'} to {'BYUC', 'EvernymV1C', 'RespectNetworkC', 'EvernymV2C'}
2016-11-03 21:36:48,982 | INFO     | stacked.py           (320) | _connsChanged | Claaaa9 now connected to EvernymV2C
2016-11-03 21:36:48,983 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa9 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV2C
Staler 'Claaaa9'. Stale transaction '3' packet '1' from '('54.193.6.155', 9745)' in 2 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '434'
Staler 'Claaaa9'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 2 at 2.478998741004034
Staler 'Claaaa9'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '0'
Staler 'Claaaa9'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.478998741004034
Staler 'Claaaa9'. Stale transaction '3' packet '1' from '('54.173.9.185', 9730)' in 2 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '473'
Staler 'Claaaa9'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 2 at 2.516277782000543
Staler 'Claaaa9'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '0'
Staler 'Claaaa9'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.586997310005245
2016-11-03 21:36:49,124 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa9 got msg from node RespectNetworkC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,124 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa9 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from RespectNetworkC
2016-11-03 21:36:49,125 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa9 cannot start catchup since received only 1 consistency proofs but need at least 3
Staler 'Claaaa9'. Stale transaction '3' packet '1' from '('52.33.22.91', 9722)' in 2 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '466'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 2 at 2.65941268500319
Staler 'Claaaa9'. Stale transaction '3' packet '1' from '('52.38.24.189', 9724)' in 2 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '482'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 2 at 2.7300029470061418
2016-11-03 21:36:49,275 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa9 got msg from node BYUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,276 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa9 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BYUC
2016-11-03 21:36:49,276 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa9 scheduling action functools.partial(<bound method LedgerManager.checkIfCPsNeeded of Claaaa9>, 0) with id 1 to run in 30 seconds
2016-11-03 21:36:49,276 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa9 cannot start catchup since received only 2 consistency proofs but need at least 3
2016-11-03 21:36:49,294 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 4 / 7 nodes
Staler 'Claaaa9'. Stale transaction '4' packet '1' from '('54.173.9.185', 9730)' in 3 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '473'
Staler 'Claaaa9'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 3 at 2.786448234001
Staler 'Claaaa9'. Stale transaction '4' packet '1' from '('54.193.6.155', 9745)' in 3 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '434'
Staler 'Claaaa9'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 3 at 2.8214610499999253
2016-11-03 21:36:49,543 | DEBUG    | stacked.py           (294) | conns | Claaaa9's connection changed from {'BYUC', 'EvernymV1C', 'RespectNetworkC', 'EvernymV2C'} to {'BYUC', 'EvernymV1C', 'RespectNetworkC', 'FCUC', 'EvernymV2C'}
2016-11-03 21:36:49,544 | INFO     | stacked.py           (320) | _connsChanged | Claaaa9 now connected to FCUC
2016-11-03 21:36:49,544 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa9 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to FCUC
Staler 'Claaaa9'. Stale transaction '4' packet '1' from '('52.33.22.91', 9722)' in 3 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '466'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 3 at 3.0920131630045944
2016-11-03 21:36:49,619 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa9 got msg from node EvernymV1C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,620 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa9 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV1C
2016-11-03 21:36:49,620 | DEBUG    | ledger_manager.py    (576) | canStartCatchUpProcess | Claaaa9 deciding on the basis of CPs {'BYUC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'EvernymV1C': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'RespectNetworkC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='])} and f 1
2016-11-03 21:36:49,620 | DEBUG    | ledger_manager.py    (656) | startCatchUpProcess | Claaaa9 started catching up with consistency proof CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=('Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='))
2016-11-03 21:36:49,620 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa9 scheduling action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa9>, 0) with id 2 to run in 5.1 seconds
2016-11-03 21:36:49,620 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa9 sending msg OrderedDict([('op', 'CATCHUP_REQ'), ('ledgerType', 0), ('seqNoStart', 8), ('seqNoEnd', 8)]) to BYUC
2016-11-03 21:36:49,625 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa9 got msg from node EvernymV2C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,625 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa9 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV2C
2016-11-03 21:36:49,625 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa9 cannot process consistency proof since in state 2 and canSync is True
2016-11-03 21:36:49,671 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa9'. Stale transaction '4' packet '1' from '('52.38.24.189', 9724)' in 3 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '482'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 3 at 3.219795454002451
Staler 'Claaaa9'. Stale transaction '3' packet '1' from '('69.144.146.171', 9734)' in 2 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '335'
Staler 'Claaaa9'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 2 at 3.26319020200026
2016-11-03 21:36:49,886 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa9 got msg from node BYUC: {'op': 'CATCHUP_REP', 'ledgerType': 0, 'txns': {'8': {'reqId': 1478156921805694, 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'type': 'CHANGE_HA', 'txnTime': 1478157003369.697, 'data': {'node_ip': '40.121.149.41', 'alias': 'WSECU', 'client_port': 9726, 'client_ip': '40.121.149.41', 'node_port': 9725}, 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN'}}, 'consProof': []}
2016-11-03 21:36:49,887 | DEBUG    | ledger_manager.py    (384) | processCatchupRep | Claaaa9 received catchup reply from BYUC: CATCHUP_REP(ledgerType=0, txns={'8': {'reqId': 1478156921805694, 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'type': 'CHANGE_HA', 'txnTime': 1478157003369.697, 'data': {'node_ip': '40.121.149.41', 'alias': 'WSECU', 'client_port': 9726, 'client_ip': '40.121.149.41', 'node_port': 9725}, 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN'}}, consProof=[])
2016-11-03 21:36:49,887 | DEBUG    | ledger_manager.py    (390) | processCatchupRep | Claaaa9 found 1 transactions in the catchup from BYUC
2016-11-03 21:36:49,887 | DEBUG    | ledger_manager.py    (399) | processCatchupRep | Claaaa9 merging all received catchups
2016-11-03 21:36:49,887 | DEBUG    | ledger_manager.py    (405) | processCatchupRep | Claaaa9 merged catchups, there are 1 of them now, from 8 to 8
2016-11-03 21:36:49,888 | DEBUG    | ledger_manager.py    (496) | hasValidCatchupReplies | Claaaa9 verifying proof for 8, 8, b'\xc8v\xe37\xc5\xb5\xf0S\x827m\x9d\xe9\xbf\x8b\xc9\xc4\xd7\xaf)\x0b\xb5\xfa\x06\x90\xb1Ed\xb8\xb9ya', b'\xd7\x99p\xfar\xf5\xd9\x9e\xb8\xd2\x05\xe3\x81\x9f\x8c\xdd2;\xfd\xab(\xf6\xbcU\tNW\xc0jDMV', []
2016-11-03 21:36:49,888 | INFO     | ledger_manager.py    (505) | hasValidCatchupReplies | Claaaa9 could not verify catchup reply CATCHUP_REP(ledgerType=0, txns={'8': {'reqId': 1478156921805694, 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'type': 'CHANGE_HA', 'txnTime': 1478157003369.697, 'data': {'node_ip': '40.121.149.41', 'alias': 'WSECU', 'client_port': 9726, 'client_ip': '40.121.149.41', 'node_port': 9725}, 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN'}}, consProof=[]) since Inconsistency: different root hashes for the same tree size
2016-11-03 21:36:49,888 | DEBUG    | ledger_manager.py    (413) | processCatchupRep | Claaaa9 processed 0 catchup replies with sequence numbers []
2016-11-03 21:36:49,903 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa9 got msg from node FCUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,903 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa9 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from FCUC
2016-11-03 21:36:49,904 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa9 cannot process consistency proof since in state 2 and canSync is True
2016-11-03 21:36:50,047 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa9'. Stale transaction '4' packet '1' from '('69.144.146.171', 9734)' in 3 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '335'
Staler 'Claaaa9'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 3 at 3.594589789005113
2016-11-03 21:36:50,425 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:50,802 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa9'. Stale transaction '1' packet 'None' from '('52.160.103.164', 9728)' in 1 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '0'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 1 at 4.493463832004636
2016-11-03 21:36:51,178 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,558 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,936 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,312 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,689 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,071 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,259 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa9 join already in process, so waiting to check for reconnects
2016-11-03 21:36:53,259 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Claaaa9 allow already in process, so waiting to check for reconnects
2016-11-03 21:36:53,259 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa9 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:53,259 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa9 nodestack is ['BYUC', 'EvernymV1C', 'RespectNetworkC', 'FCUC', 'EvernymV2C', 'estate_8598a0d7a1df11e6ac2c6807152028e4', 'BIGC']
2016-11-03 21:36:53,259 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa9 matched remote is 2 ('54.193.6.155', 9745)
2016-11-03 21:36:53,260 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa9 matched remote is 3 ('52.33.22.91', 9722)
2016-11-03 21:36:53,260 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa9 matched remote is 4 ('54.173.9.185', 9730)
2016-11-03 21:36:53,260 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa9 matched remote is 5 ('69.144.146.171', 9734)
2016-11-03 21:36:53,260 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa9 matched remote is 6 ('52.38.24.189', 9724)
2016-11-03 21:36:53,260 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa9 unmatched remote is 7 ('13.93.218.255', 9726)
2016-11-03 21:36:53,260 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa9 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_8598a0d7a1df11e6ac2c6807152028e4
2016-11-03 21:36:53,260 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa9 matched remote is 8 ('52.160.103.164', 9728)
2016-11-03 21:36:53,260 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa9 next check for retries in 6.00 seconds
2016-11-03 21:36:53,448 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,824 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,010 | DEBUG    | stacked.py           (294) | conns | Claaaa9's connection changed from {'BYUC', 'EvernymV1C', 'RespectNetworkC', 'FCUC', 'EvernymV2C'} to {'BYUC', 'EvernymV1C', 'RespectNetworkC', 'FCUC', 'EvernymV2C', 'BIGC'}
2016-11-03 21:36:54,010 | INFO     | stacked.py           (320) | _connsChanged | Claaaa9 now connected to BIGC
2016-11-03 21:36:54,011 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa9 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BIGC
2016-11-03 21:36:54,200 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 6 / 7 nodes
2016-11-03 21:36:54,200 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkIfConnectedToAll) succeeded with 1.07 seconds to spare
2016-11-03 21:36:54,205 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'identifier': '2zvD8jce4JcRmjMmjmXHpcuQenPVaSgDiHAeDJZUXB4o', 'reqId': 1478189214202040, 'operation': {'type': 'ATTRIB', 'raw': '0366cb545c8b579ddaecf1b9663300ed09c23b91d53af2379eb9142adf7a39c5'}, 'signature': None} into identifier:2zvD8jce4JcRmjMmjmXHpcuQenPVaSgDiHAeDJZUXB4o|operation:raw:0366cb545c8b579ddaecf1b9663300ed09c23b91d53af2379eb9142adf7a39c5|type:ATTRIB|reqId:1478189214202040
2016-11-03 21:36:54,206 | DEBUG    | client.py            (228) | submitReqs | Claaaa9 pending request since in mode 1 and connected to {'BYUC', 'EvernymV1C', 'RespectNetworkC', 'FCUC', 'EvernymV2C', 'BIGC'} nodes
2016-11-03 21:36:54,206 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'operation': {'raw': '{"b1TR72OvVayqdS6YBnZm_615575": "118804171108_3CagkZYWL9wEFrjApOK8Xmib7VhP24qSD0ItoU1sQzBdfcxM5y"}', 'type': 'ATTRIB'}, 'signature': '2nh9LTt4ZgTjDw2uHjt5bEirysfXXaNiBtuv5VhJkuq1Gp4qqfqpzB2UXYYsuytbu7wakLJJNAdsSxFF4KGkDUwA', 'identifier': '2zvD8jce4JcRmjMmjmXHpcuQenPVaSgDiHAeDJZUXB4o', 'reqId': 1478189214202040}
2016-11-03 21:36:54,206 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa9 sending request Request: {'operation': {'raw': '{"b1TR72OvVayqdS6YBnZm_615575": "118804171108_3CagkZYWL9wEFrjApOK8Xmib7VhP24qSD0ItoU1sQzBdfcxM5y"}', 'type': 'ATTRIB'}, 'signature': '2nh9LTt4ZgTjDw2uHjt5bEirysfXXaNiBtuv5VhJkuq1Gp4qqfqpzB2UXYYsuytbu7wakLJJNAdsSxFF4KGkDUwA', 'identifier': '2zvD8jce4JcRmjMmjmXHpcuQenPVaSgDiHAeDJZUXB4o', 'reqId': 1478189214202040}
2016-11-03 21:36:54,727 | DEBUG    | has_action_queue.py  (60) | _serviceActions | Claaaa9 running action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa9>, 0) with id 2
Staler 'Claaaa9'. Stale transaction '3' packet '1' from '('52.160.103.164', 9728)' in 2 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '475'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 2 at 8.974683088999882
Staler 'Claaaa9'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '475'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 11.026183023001067
Staler 'Claaaa9'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '475'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 11.026183023001067
2016-11-03 21:36:59,248 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa9', signerId='2zvD8jce4JcRmjMmjmXHpcuQenPVaSgDiHAeDJZUXB4o', reqId=1478189214202040, transactionType='ATTRIB', sentAt=1478189214.2059515, quorumAt='', latency=5.042403936386108, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:36:59,248 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.46 seconds to spare
2016-11-03 21:36:59,249 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 5.047695636749268
        Average latency: 5.042403936386108
        Throughput: 0.0
        Error rate: 0.19811020155803277
        Succeeded: 0
        Failed: 1
        Query Time: 0
        ================================
        
2016-11-03 21:36:59,249 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'identifier': '2zvD8jce4JcRmjMmjmXHpcuQenPVaSgDiHAeDJZUXB4o', 'reqId': 1478189219249585, 'operation': {'type': 'ATTRIB', 'raw': 'd5c92534d046933d389178fa09fefea4b74d3159076305672775320ddc7dedf8'}, 'signature': None} into identifier:2zvD8jce4JcRmjMmjmXHpcuQenPVaSgDiHAeDJZUXB4o|operation:raw:d5c92534d046933d389178fa09fefea4b74d3159076305672775320ddc7dedf8|type:ATTRIB|reqId:1478189219249585
2016-11-03 21:36:59,250 | DEBUG    | client.py            (228) | submitReqs | Claaaa9 pending request since in mode 1 and connected to {'BYUC', 'EvernymV1C', 'RespectNetworkC', 'FCUC', 'EvernymV2C', 'BIGC'} nodes
2016-11-03 21:36:59,253 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'operation': {'raw': '{"2QvnpwI0KgkGFOt8V3NE_359520": "439494129994_83Laf9lBh7xtbMTXcnsZODwizvmHrVS501gANY2eKoEJPCFRpI"}', 'type': 'ATTRIB'}, 'signature': '4vJEaLaJ757AGi9z93vBNXjheurfyw3zrX59SVgCkCMCihh6dwaM4EWgXNCnMqiGVBK6Ax3BHTBUsf3uPiUjAFy', 'identifier': '2zvD8jce4JcRmjMmjmXHpcuQenPVaSgDiHAeDJZUXB4o', 'reqId': 1478189219249585}
2016-11-03 21:36:59,254 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa9 sending request Request: {'operation': {'raw': '{"2QvnpwI0KgkGFOt8V3NE_359520": "439494129994_83Laf9lBh7xtbMTXcnsZODwizvmHrVS501gANY2eKoEJPCFRpI"}', 'type': 'ATTRIB'}, 'signature': '4vJEaLaJ757AGi9z93vBNXjheurfyw3zrX59SVgCkCMCihh6dwaM4EWgXNCnMqiGVBK6Ax3BHTBUsf3uPiUjAFy', 'identifier': '2zvD8jce4JcRmjMmjmXHpcuQenPVaSgDiHAeDJZUXB4o', 'reqId': 1478189219249585}
2016-11-03 21:36:59,273 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa9 join already in process, so waiting to check for reconnects
2016-11-03 21:36:59,273 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa9 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:59,273 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa9 nodestack is ['BYUC', 'EvernymV1C', 'RespectNetworkC', 'FCUC', 'EvernymV2C', 'estate_8598a0d7a1df11e6ac2c6807152028e4', 'BIGC']
2016-11-03 21:36:59,273 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa9 matched remote is 2 ('54.193.6.155', 9745)
2016-11-03 21:36:59,274 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa9 matched remote is 3 ('52.33.22.91', 9722)
2016-11-03 21:36:59,274 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa9 matched remote is 4 ('54.173.9.185', 9730)
2016-11-03 21:36:59,274 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa9 matched remote is 5 ('69.144.146.171', 9734)
2016-11-03 21:36:59,274 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa9 matched remote is 6 ('52.38.24.189', 9724)
2016-11-03 21:36:59,274 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa9 unmatched remote is 7 ('13.93.218.255', 9726)
2016-11-03 21:36:59,274 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa9 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_8598a0d7a1df11e6ac2c6807152028e4
2016-11-03 21:36:59,278 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa9 matched remote is 8 ('52.160.103.164', 9728)
2016-11-03 21:36:59,278 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa9 next check for retries in 6.00 seconds
Staler 'Claaaa9'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '475'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.796735150004679
Staler 'Claaaa9'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa9'. Unknown correspondent estate id '475'
Staler 'Claaaa9'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.796735150004679
2016-11-03 21:37:00,334 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa9 got msg from node BIGC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:37:00,335 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa9 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BIGC
2016-11-03 21:37:00,335 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa9 cannot process consistency proof since in state 2 and canSync is True
Stalent 'Claaaa9'. Stale transaction '0' packet '0' from '('52.160.103.164', 9728)' in 1 nacking ...
Stalent 'Claaaa9'. Unknown initiator estate id '475'
Stalent 'Claaaa9'. Do Nack of ('52.160.103.164', 9728) in 1 at 14.993366975002573
2016-11-03 21:37:04,294 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa9', signerId='2zvD8jce4JcRmjMmjmXHpcuQenPVaSgDiHAeDJZUXB4o', reqId=1478189219249585, transactionType='ATTRIB', sentAt=1478189219.250106, quorumAt='', latency=5.044490575790405, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:37:04,294 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.46 seconds to spare
2016-11-03 21:37:04,295 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 10.09361720085144
        Average latency: 5.043447256088257
        Throughput: 0.0
        Error rate: 0.19814502176992518
        Succeeded: 0
        Failed: 2
        Query Time: 0
        ================================
        
2016-11-03 21:37:04,295 | DEBUG    | gen_load_ratcheting  (326) | main | Sent 1 ATTRIB requests
2016-11-03 21:37:04,295 | INFO     | looper.py            (253) | shutdown | Looper shutting down now...
2016-11-03 21:37:04,306 | DEBUG    | motor.py             (34) | set_status | Claaaa9 changing status from started_hungry to stopping
2016-11-03 21:37:04,306 | INFO     | stacked.py           (82) | stop | stack Claaaa9 stopped
2016-11-03 21:37:04,306 | DEBUG    | motor.py             (34) | set_status | Claaaa9 changing status from stopping to stopped
2016-11-03 21:37:04,306 | INFO     | looper.py            (260) | shutdown | Looper shut down in 0.011 seconds.
2016-11-03 21:37:04,352 | DEBUG    | base_events.py       (410) | close | Close <_UnixSelectorEventLoop running=False closed=False debug=True>
