2016-11-03 21:36:43,500 | INFO     | log.py               (128) | setupLogging | Choosing RAET log level 1
2016-11-03 21:36:45,781 | DEBUG    | testable.py          (126) | decorator | in SpyableTestClient added spy on __init__
2016-11-03 21:36:45,781 | WARNING  | testable.py          (134) | decorator | method <function Client.handleOneNodeMsg at 0x7f49d4957ea0> not found, so no spy added
2016-11-03 21:36:45,807 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on __init__
2016-11-03 21:36:45,807 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterReqLatencyTooHigh
2016-11-03 21:36:45,815 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterThroughputTooLow
2016-11-03 21:36:45,815 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on sendThroughput
2016-11-03 21:36:45,818 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on __init__
2016-11-03 21:36:45,818 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on catchupCompleted
2016-11-03 21:36:45,818 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on processConsistencyProofReq
2016-11-03 21:36:45,818 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on startCatchUpProcess
2016-11-03 21:36:45,829 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on __init__
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on addToPrePrepares
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canProcessPrePrepare
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canSendPrepare
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doOrder
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrePrepare
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrepare
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on isValidPrepare
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on orderPendingCommit
2016-11-03 21:36:45,830 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processCommit
2016-11-03 21:36:45,831 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrePrepare
2016-11-03 21:36:45,831 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrepare
2016-11-03 21:36:45,848 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on __init__
2016-11-03 21:36:45,849 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on checkPerformance
2016-11-03 21:36:45,849 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on decidePrimaries
2016-11-03 21:36:45,849 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on discard
2016-11-03 21:36:45,849 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on eatTestMsg
2016-11-03 21:36:45,849 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on forward
2016-11-03 21:36:45,849 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleInvalidClientMsg
2016-11-03 21:36:45,849 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleOneNodeMsg
2016-11-03 21:36:45,849 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToClientInBox
2016-11-03 21:36:45,850 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToNodeInBox
2016-11-03 21:36:45,850 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processInstanceChange
2016-11-03 21:36:45,850 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processOrdered
2016-11-03 21:36:45,850 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processPropagate
2016-11-03 21:36:45,850 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processRequest
2016-11-03 21:36:45,850 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on propagate
2016-11-03 21:36:45,850 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousClient
2016-11-03 21:36:45,850 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousNode
2016-11-03 21:36:45,850 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on send
2016-11-03 21:36:45,850 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on sendInstanceChange
2016-11-03 21:36:45,851 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on startViewChange
Loading module /home/lovesh/.virtualenvs/sovrin-dev/lib/python3.5/site-packages/anoncreds_dev-0.1.8-py3.5.egg/config/config-crypto-example1.py
Module loaded.
2016-11-03 21:36:46,450 | DEBUG    | gen_load_ratcheting  (280) | main | Results file: /home/lovesh/dev/evernym/sovrin-priv/scripts/perf_results_1_2_1478189206.csv
2016-11-03 21:36:46,450 | INFO     | gen_load_ratcheting  (136) | _spawnClient | Seed for client Claaaa10 is b'000000000000000000000000Claaaa10', its len is 32
2016-11-03 21:36:46,451 | DEBUG    | ledger.py            (164) | start | Starting ledger...
2016-11-03 21:36:46,452 | DEBUG    | ledger.py            (69) | recoverTree | Recovering tree from transaction log
2016-11-03 21:36:46,492 | INFO     | client.py            (121) | __init__ | Client Claaaa10 initialized with the following node registry:
2016-11-03 21:36:46,492 | INFO     | client.py            (128) | __init__ |     EvernymV1C      listens at 52.33.22.91    on port 9722
2016-11-03 21:36:46,493 | INFO     | client.py            (128) | __init__ |     EvernymV2C      listens at 52.38.24.189   on port 9724
2016-11-03 21:36:46,493 | INFO     | client.py            (128) | __init__ |     WSECUC          listens at 13.93.218.255  on port 9726
2016-11-03 21:36:46,493 | INFO     | client.py            (128) | __init__ |     BIGC            listens at 52.160.103.164 on port 9728
2016-11-03 21:36:46,493 | INFO     | client.py            (128) | __init__ |     RespectNetworkC listens at 54.173.9.185   on port 9730
2016-11-03 21:36:46,493 | INFO     | client.py            (128) | __init__ |     FCUC            listens at 69.144.146.171 on port 9734
2016-11-03 21:36:46,493 | INFO     | client.py            (128) | __init__ |     BYUC            listens at 54.193.6.155   on port 9745
2016-11-03 21:36:46,493 | DEBUG    | plugin_helper.py     (25) | loadPlugins | Plugin loading started to load plugins from basedir: /home/lovesh/.sovrin
2016-11-03 21:36:47,220 | DEBUG    | plugin_helper.py     (68) | loadPlugins | Total plugins loaded from basedir /home/lovesh/.sovrin are : 1
2016-11-03 21:36:47,220 | DEBUG    | client.py            (148) | __init__ | total plugins loaded in client: 1
2016-11-03 21:36:47,220 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
2016-11-03 21:36:47,221 | DEBUG    | looper.py            (121) | __init__ | Setting handler for SIGINT
2016-11-03 21:36:47,221 | DEBUG    | motor.py             (34) | set_status | Claaaa10 changing status from stopped to starting
2016-11-03 21:36:47,221 | INFO     | stacked.py           (75) | start | stack Claaaa10 starting at ('0.0.0.0', 5995) in always mode
2016-11-03 21:36:47,221 | INFO     | stacked.py           (851) | start | Claaaa10 listening for other nodes at 0.0.0.0:5995
2016-11-03 21:36:47,222 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa10 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:47,222 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa10 nodestack is []
2016-11-03 21:36:47,222 | DEBUG    | stacked.py           (504) | connectToMissing | Claaaa10 found the following missing connections: FCUC, RespectNetworkC, WSECUC, BIGC, BYUC, EvernymV2C, EvernymV1C
2016-11-03 21:36:47,471 | INFO     | stacked.py           (456) | connect | Claaaa10 looking for FCUC at 69.144.146.171:9734
2016-11-03 21:36:47,490 | INFO     | stacked.py           (456) | connect | Claaaa10 looking for RespectNetworkC at 54.173.9.185:9730
2016-11-03 21:36:47,509 | INFO     | stacked.py           (456) | connect | Claaaa10 looking for WSECUC at 13.93.218.255:9726
2016-11-03 21:36:47,528 | INFO     | stacked.py           (456) | connect | Claaaa10 looking for BIGC at 52.160.103.164:9728
2016-11-03 21:36:47,547 | INFO     | stacked.py           (456) | connect | Claaaa10 looking for BYUC at 54.193.6.155:9745
2016-11-03 21:36:47,567 | INFO     | stacked.py           (456) | connect | Claaaa10 looking for EvernymV2C at 52.38.24.189:9724
2016-11-03 21:36:47,625 | INFO     | stacked.py           (456) | connect | Claaaa10 looking for EvernymV1C at 52.33.22.91:9722
2016-11-03 21:36:47,625 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa10 next check for retries in 6.00 seconds
2016-11-03 21:36:47,629 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 21:36:48,005 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Staler 'Claaaa10'. Stale transaction '1' packet 'None' from '('54.193.6.155', 9745)' in 1 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '0'
Staler 'Claaaa10'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 1 at 1.713215728996147
Staler 'Claaaa10'. Stale transaction '1' packet 'None' from '('54.173.9.185', 9730)' in 1 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '0'
Staler 'Claaaa10'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 1 at 1.770304142999521
Staler 'Claaaa10'. Stale transaction '1' packet 'None' from '('52.33.22.91', 9722)' in 1 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '0'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 1 at 1.770304142999521
Staler 'Claaaa10'. Stale transaction '1' packet 'None' from '('52.38.24.189', 9724)' in 1 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '0'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 1 at 1.770304142999521
2016-11-03 21:36:48,383 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Staler 'Claaaa10'. Stale transaction '1' packet 'None' from '('52.33.22.91', 9722)' in 1 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '0'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 1 at 1.974155003001215
Staler 'Claaaa10'. Stale transaction '1' packet 'None' from '('52.38.24.189', 9724)' in 1 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '0'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 1 at 1.993424676998984
2016-11-03 21:36:48,764 | DEBUG    | stacked.py           (294) | conns | Claaaa10's connection changed from set() to {'BYUC'}
2016-11-03 21:36:48,765 | INFO     | stacked.py           (320) | _connsChanged | Claaaa10 now connected to BYUC
2016-11-03 21:36:48,765 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa10 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BYUC
2016-11-03 21:36:48,765 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 1 / 7 nodes
2016-11-03 21:36:48,837 | DEBUG    | stacked.py           (294) | conns | Claaaa10's connection changed from {'BYUC'} to {'RespectNetworkC', 'BYUC'}
2016-11-03 21:36:48,837 | INFO     | stacked.py           (320) | _connsChanged | Claaaa10 now connected to RespectNetworkC
2016-11-03 21:36:48,837 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa10 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to RespectNetworkC
2016-11-03 21:36:48,901 | DEBUG    | stacked.py           (294) | conns | Claaaa10's connection changed from {'RespectNetworkC', 'BYUC'} to {'EvernymV2C', 'RespectNetworkC', 'BYUC'}
2016-11-03 21:36:48,901 | INFO     | stacked.py           (320) | _connsChanged | Claaaa10 now connected to EvernymV2C
2016-11-03 21:36:48,901 | DEBUG    | motor.py             (34) | set_status | Claaaa10 changing status from starting to started_hungry
2016-11-03 21:36:48,901 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa10 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV2C
2016-11-03 21:36:48,960 | DEBUG    | stacked.py           (294) | conns | Claaaa10's connection changed from {'EvernymV2C', 'RespectNetworkC', 'BYUC'} to {'EvernymV2C', 'RespectNetworkC', 'BYUC', 'EvernymV1C'}
2016-11-03 21:36:48,960 | INFO     | stacked.py           (320) | _connsChanged | Claaaa10 now connected to EvernymV1C
2016-11-03 21:36:48,960 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa10 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV1C
Staler 'Claaaa10'. Stale transaction '3' packet '1' from '('54.193.6.155', 9745)' in 2 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '432'
Staler 'Claaaa10'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 2 at 2.5042358089995105
Staler 'Claaaa10'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '0'
Staler 'Claaaa10'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.5042358089995105
Staler 'Claaaa10'. Stale transaction '3' packet '1' from '('54.173.9.185', 9730)' in 2 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '471'
Staler 'Claaaa10'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 2 at 2.56016628100042
Staler 'Claaaa10'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '0'
Staler 'Claaaa10'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.6040306219947524
2016-11-03 21:36:49,110 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa10 got msg from node BYUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,110 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa10 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BYUC
2016-11-03 21:36:49,110 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa10 cannot start catchup since received only 1 consistency proofs but need at least 3
2016-11-03 21:36:49,144 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 4 / 7 nodes
Staler 'Claaaa10'. Stale transaction '3' packet '1' from '('52.38.24.189', 9724)' in 2 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '480'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 2 at 2.656247059996531
Staler 'Claaaa10'. Stale transaction '3' packet '1' from '('52.33.22.91', 9722)' in 2 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '464'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 2 at 2.6768525459992816
2016-11-03 21:36:49,260 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa10 got msg from node RespectNetworkC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,260 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa10 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from RespectNetworkC
2016-11-03 21:36:49,260 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa10 scheduling action functools.partial(<bound method LedgerManager.checkIfCPsNeeded of Claaaa10>, 0) with id 1 to run in 30 seconds
2016-11-03 21:36:49,260 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa10 cannot start catchup since received only 2 consistency proofs but need at least 3
Staler 'Claaaa10'. Stale transaction '4' packet '1' from '('54.193.6.155', 9745)' in 3 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '432'
Staler 'Claaaa10'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 3 at 2.805863950001367
Staler 'Claaaa10'. Stale transaction '4' packet '1' from '('54.173.9.185', 9730)' in 3 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '471'
Staler 'Claaaa10'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 3 at 2.8653751099991496
2016-11-03 21:36:49,474 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa10 got msg from node EvernymV1C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,474 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa10 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV1C
2016-11-03 21:36:49,474 | DEBUG    | ledger_manager.py    (576) | canStartCatchUpProcess | Claaaa10 deciding on the basis of CPs {'EvernymV1C': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'RespectNetworkC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'BYUC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='])} and f 1
2016-11-03 21:36:49,474 | DEBUG    | ledger_manager.py    (656) | startCatchUpProcess | Claaaa10 started catching up with consistency proof CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=('Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='))
2016-11-03 21:36:49,475 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa10 scheduling action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa10>, 0) with id 2 to run in 5.1 seconds
2016-11-03 21:36:49,475 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa10 sending msg OrderedDict([('op', 'CATCHUP_REQ'), ('ledgerType', 0), ('seqNoStart', 8), ('seqNoEnd', 8)]) to EvernymV2C
2016-11-03 21:36:49,520 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 4 / 7 nodes
2016-11-03 21:36:49,565 | DEBUG    | stacked.py           (294) | conns | Claaaa10's connection changed from {'EvernymV2C', 'RespectNetworkC', 'BYUC', 'EvernymV1C'} to {'FCUC', 'EvernymV2C', 'RespectNetworkC', 'BYUC', 'EvernymV1C'}
2016-11-03 21:36:49,566 | INFO     | stacked.py           (320) | _connsChanged | Claaaa10 now connected to FCUC
2016-11-03 21:36:49,566 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa10 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to FCUC
Staler 'Claaaa10'. Stale transaction '4' packet '1' from '('52.33.22.91', 9722)' in 3 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '464'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 3 at 3.1238152099977015
Staler 'Claaaa10'. Stale transaction '4' packet '1' from '('52.38.24.189', 9724)' in 3 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '480'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 3 at 3.145544824001263
2016-11-03 21:36:49,665 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa10 got msg from node EvernymV2C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,666 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa10 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV2C
2016-11-03 21:36:49,666 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa10 cannot process consistency proof since in state 2 and canSync is True
Staler 'Claaaa10'. Stale transaction '3' packet '1' from '('69.144.146.171', 9734)' in 2 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '333'
Staler 'Claaaa10'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 2 at 3.283716097997967
2016-11-03 21:36:49,814 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa10 got msg from node EvernymV2C: {'op': 'CATCHUP_REP', 'ledgerType': 0, 'txns': {'8': {'reqId': 1478156921805694, 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'data': {'node_port': 9725, 'client_ip': '40.121.149.41', 'client_port': 9726, 'node_ip': '40.121.149.41', 'alias': 'WSECU'}, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'type': 'CHANGE_HA', 'txnTime': 1478157003369.697}}, 'consProof': []}
2016-11-03 21:36:49,815 | DEBUG    | ledger_manager.py    (384) | processCatchupRep | Claaaa10 received catchup reply from EvernymV2C: CATCHUP_REP(ledgerType=0, txns={'8': {'reqId': 1478156921805694, 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'data': {'node_port': 9725, 'client_ip': '40.121.149.41', 'client_port': 9726, 'node_ip': '40.121.149.41', 'alias': 'WSECU'}, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'type': 'CHANGE_HA', 'txnTime': 1478157003369.697}}, consProof=[])
2016-11-03 21:36:49,815 | DEBUG    | ledger_manager.py    (390) | processCatchupRep | Claaaa10 found 1 transactions in the catchup from EvernymV2C
2016-11-03 21:36:49,815 | DEBUG    | ledger_manager.py    (399) | processCatchupRep | Claaaa10 merging all received catchups
2016-11-03 21:36:49,815 | DEBUG    | ledger_manager.py    (405) | processCatchupRep | Claaaa10 merged catchups, there are 1 of them now, from 8 to 8
2016-11-03 21:36:49,816 | DEBUG    | ledger_manager.py    (496) | hasValidCatchupReplies | Claaaa10 verifying proof for 8, 8, b'\xc8v\xe37\xc5\xb5\xf0S\x827m\x9d\xe9\xbf\x8b\xc9\xc4\xd7\xaf)\x0b\xb5\xfa\x06\x90\xb1Ed\xb8\xb9ya', b'\xd7\x99p\xfar\xf5\xd9\x9e\xb8\xd2\x05\xe3\x81\x9f\x8c\xdd2;\xfd\xab(\xf6\xbcU\tNW\xc0jDMV', []
2016-11-03 21:36:49,816 | INFO     | ledger_manager.py    (505) | hasValidCatchupReplies | Claaaa10 could not verify catchup reply CATCHUP_REP(ledgerType=0, txns={'8': {'reqId': 1478156921805694, 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'data': {'node_port': 9725, 'client_ip': '40.121.149.41', 'client_port': 9726, 'node_ip': '40.121.149.41', 'alias': 'WSECU'}, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'type': 'CHANGE_HA', 'txnTime': 1478157003369.697}}, consProof=[]) since Inconsistency: different root hashes for the same tree size
2016-11-03 21:36:49,816 | DEBUG    | ledger_manager.py    (413) | processCatchupRep | Claaaa10 processed 0 catchup replies with sequence numbers []
2016-11-03 21:36:49,896 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:49,914 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa10 got msg from node FCUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,915 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa10 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from FCUC
2016-11-03 21:36:49,915 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa10 cannot process consistency proof since in state 2 and canSync is True
Staler 'Claaaa10'. Stale transaction '4' packet '1' from '('69.144.146.171', 9734)' in 3 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '333'
Staler 'Claaaa10'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 3 at 3.6264274009954534
2016-11-03 21:36:50,273 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:50,649 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa10'. Stale transaction '1' packet 'None' from '('52.160.103.164', 9728)' in 1 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '0'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 1 at 4.508756849994825
2016-11-03 21:36:51,026 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,402 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,779 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,156 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,533 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,909 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,224 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa10 join already in process, so waiting to check for reconnects
2016-11-03 21:36:53,224 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Claaaa10 allow already in process, so waiting to check for reconnects
2016-11-03 21:36:53,224 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa10 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:53,225 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa10 nodestack is ['FCUC', 'RespectNetworkC', 'estate_8593f0f2a1df11e6ac2c6807152028e4', 'BIGC', 'BYUC', 'EvernymV2C', 'EvernymV1C']
2016-11-03 21:36:53,225 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa10 matched remote is 2 ('69.144.146.171', 9734)
2016-11-03 21:36:53,225 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa10 matched remote is 3 ('54.173.9.185', 9730)
2016-11-03 21:36:53,225 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa10 unmatched remote is 4 ('13.93.218.255', 9726)
2016-11-03 21:36:53,225 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa10 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_8593f0f2a1df11e6ac2c6807152028e4
2016-11-03 21:36:53,225 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa10 matched remote is 5 ('52.160.103.164', 9728)
2016-11-03 21:36:53,225 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa10 matched remote is 6 ('54.193.6.155', 9745)
2016-11-03 21:36:53,225 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa10 matched remote is 7 ('52.38.24.189', 9724)
2016-11-03 21:36:53,225 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa10 matched remote is 8 ('52.33.22.91', 9722)
2016-11-03 21:36:53,226 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa10 next check for retries in 6.00 seconds
2016-11-03 21:36:53,286 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,663 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,013 | DEBUG    | stacked.py           (294) | conns | Claaaa10's connection changed from {'FCUC', 'EvernymV2C', 'RespectNetworkC', 'BYUC', 'EvernymV1C'} to {'FCUC', 'RespectNetworkC', 'BIGC', 'BYUC', 'EvernymV2C', 'EvernymV1C'}
2016-11-03 21:36:54,013 | INFO     | stacked.py           (320) | _connsChanged | Claaaa10 now connected to BIGC
2016-11-03 21:36:54,013 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa10 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BIGC
2016-11-03 21:36:54,041 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 6 / 7 nodes
2016-11-03 21:36:54,041 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkIfConnectedToAll) succeeded with 1.09 seconds to spare
2016-11-03 21:36:54,044 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'operation': {'type': 'ATTRIB', 'raw': '32064d6f080ca81367ea690b969919d770e6b9ac707732831f989cd1199f212e'}, 'reqId': 1478189214043601, 'identifier': '6Qyc1o5wowcCEBuFQeRk2dFo8vkLz3fh7Qk8Ex2ExpoR', 'signature': None} into identifier:6Qyc1o5wowcCEBuFQeRk2dFo8vkLz3fh7Qk8Ex2ExpoR|operation:raw:32064d6f080ca81367ea690b969919d770e6b9ac707732831f989cd1199f212e|type:ATTRIB|reqId:1478189214043601
2016-11-03 21:36:54,044 | DEBUG    | client.py            (228) | submitReqs | Claaaa10 pending request since in mode 1 and connected to {'FCUC', 'RespectNetworkC', 'BIGC', 'BYUC', 'EvernymV2C', 'EvernymV1C'} nodes
2016-11-03 21:36:54,044 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'reqId': 1478189214043601, 'identifier': '6Qyc1o5wowcCEBuFQeRk2dFo8vkLz3fh7Qk8Ex2ExpoR', 'signature': '4zVCy9Af5Cf4JAHEYkVbMsvmkMRdaU1ZW6kx9YizB3hzRjgJEYKtYfkiq51nofHkvVYUfJ7DSmo1GJdjr2bFbetV', 'operation': {'type': 'ATTRIB', 'raw': '{"ejm7MId4SKgYCoiOUuzF_717169": "365795022849_X8gph4uFIwnMB1maJlLNT3RKdbt6PkYWeVS7zOGoU20xC59rQq"}'}}
2016-11-03 21:36:54,044 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa10 sending request Request: {'reqId': 1478189214043601, 'identifier': '6Qyc1o5wowcCEBuFQeRk2dFo8vkLz3fh7Qk8Ex2ExpoR', 'signature': '4zVCy9Af5Cf4JAHEYkVbMsvmkMRdaU1ZW6kx9YizB3hzRjgJEYKtYfkiq51nofHkvVYUfJ7DSmo1GJdjr2bFbetV', 'operation': {'type': 'ATTRIB', 'raw': '{"ejm7MId4SKgYCoiOUuzF_717169": "365795022849_X8gph4uFIwnMB1maJlLNT3RKdbt6PkYWeVS7zOGoU20xC59rQq"}'}}
2016-11-03 21:36:54,575 | DEBUG    | has_action_queue.py  (60) | _serviceActions | Claaaa10 running action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa10>, 0) with id 2
Staler 'Claaaa10'. Stale transaction '3' packet '1' from '('52.160.103.164', 9728)' in 2 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '473'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 2 at 8.994606538995868
Staler 'Claaaa10'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '473'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 11.040027750001173
Staler 'Claaaa10'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '473'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 11.040027750001173
2016-11-03 21:36:59,080 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa10', signerId='6Qyc1o5wowcCEBuFQeRk2dFo8vkLz3fh7Qk8Ex2ExpoR', reqId=1478189214043601, transactionType='ATTRIB', sentAt=1478189214.04456, quorumAt='', latency=5.035798788070679, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:36:59,080 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.46 seconds to spare
2016-11-03 21:36:59,081 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 5.038237571716309
        Average latency: 5.035798788070679
        Throughput: 0.0
        Error rate: 0.1984821052531954
        Succeeded: 0
        Failed: 1
        Query Time: 0
        ================================
        
2016-11-03 21:36:59,082 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'operation': {'type': 'ATTRIB', 'raw': 'bb707e7ea23076f974ac5b60d0fba9c5610d956ec0cbe22452ed4634f6803bf1'}, 'reqId': 1478189219081847, 'identifier': '6Qyc1o5wowcCEBuFQeRk2dFo8vkLz3fh7Qk8Ex2ExpoR', 'signature': None} into identifier:6Qyc1o5wowcCEBuFQeRk2dFo8vkLz3fh7Qk8Ex2ExpoR|operation:raw:bb707e7ea23076f974ac5b60d0fba9c5610d956ec0cbe22452ed4634f6803bf1|type:ATTRIB|reqId:1478189219081847
2016-11-03 21:36:59,082 | DEBUG    | client.py            (228) | submitReqs | Claaaa10 pending request since in mode 1 and connected to {'FCUC', 'RespectNetworkC', 'BIGC', 'BYUC', 'EvernymV2C', 'EvernymV1C'} nodes
2016-11-03 21:36:59,082 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'reqId': 1478189219081847, 'identifier': '6Qyc1o5wowcCEBuFQeRk2dFo8vkLz3fh7Qk8Ex2ExpoR', 'signature': '4ETm9YmDPUZPsZzGxDpnf7wvtK1eeXZuzZozXid1kx4bhrUuNj79jJpWSrKJ9WssG6x8Z1cj6QNhrpRSB1ZnN61x', 'operation': {'type': 'ATTRIB', 'raw': '{"3dOsnRmpW4xkT9XYCUl1_410048": "563485445749_pqkij5htROnmuEJVv3Zx02s4wCXIBcHarlb6oN98MFdSK1LWU7"}'}}
2016-11-03 21:36:59,082 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa10 sending request Request: {'reqId': 1478189219081847, 'identifier': '6Qyc1o5wowcCEBuFQeRk2dFo8vkLz3fh7Qk8Ex2ExpoR', 'signature': '4ETm9YmDPUZPsZzGxDpnf7wvtK1eeXZuzZozXid1kx4bhrUuNj79jJpWSrKJ9WssG6x8Z1cj6QNhrpRSB1ZnN61x', 'operation': {'type': 'ATTRIB', 'raw': '{"3dOsnRmpW4xkT9XYCUl1_410048": "563485445749_pqkij5htROnmuEJVv3Zx02s4wCXIBcHarlb6oN98MFdSK1LWU7"}'}}
2016-11-03 21:36:59,230 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa10 join already in process, so waiting to check for reconnects
2016-11-03 21:36:59,230 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa10 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:59,230 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa10 nodestack is ['FCUC', 'RespectNetworkC', 'estate_8593f0f2a1df11e6ac2c6807152028e4', 'BIGC', 'BYUC', 'EvernymV2C', 'EvernymV1C']
2016-11-03 21:36:59,230 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa10 matched remote is 2 ('69.144.146.171', 9734)
2016-11-03 21:36:59,230 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa10 matched remote is 3 ('54.173.9.185', 9730)
2016-11-03 21:36:59,231 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa10 unmatched remote is 4 ('13.93.218.255', 9726)
2016-11-03 21:36:59,231 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa10 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_8593f0f2a1df11e6ac2c6807152028e4
2016-11-03 21:36:59,231 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa10 matched remote is 5 ('52.160.103.164', 9728)
2016-11-03 21:36:59,231 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa10 matched remote is 6 ('54.193.6.155', 9745)
2016-11-03 21:36:59,231 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa10 matched remote is 7 ('52.38.24.189', 9724)
2016-11-03 21:36:59,231 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa10 matched remote is 8 ('52.33.22.91', 9722)
2016-11-03 21:36:59,231 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa10 next check for retries in 6.00 seconds
Staler 'Claaaa10'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '473'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.816787648996979
Staler 'Claaaa10'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa10'. Unknown correspondent estate id '473'
Staler 'Claaaa10'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.841653857998608
2016-11-03 21:37:00,356 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa10 got msg from node BIGC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:37:00,356 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa10 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BIGC
2016-11-03 21:37:00,356 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa10 cannot process consistency proof since in state 2 and canSync is True
Stalent 'Claaaa10'. Stale transaction '0' packet '0' from '('52.160.103.164', 9728)' in 1 nacking ...
Stalent 'Claaaa10'. Unknown initiator estate id '473'
Stalent 'Claaaa10'. Do Nack of ('52.160.103.164', 9728) in 1 at 15.016384233997087
2016-11-03 21:37:04,137 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa10', signerId='6Qyc1o5wowcCEBuFQeRk2dFo8vkLz3fh7Qk8Ex2ExpoR', reqId=1478189219081847, transactionType='ATTRIB', sentAt=1478189219.0824, quorumAt='', latency=5.054816246032715, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:37:04,137 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.45 seconds to spare
2016-11-03 21:37:04,137 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 10.094841003417969
        Average latency: 5.045307517051697
        Throughput: 0.0
        Error rate: 0.19812100055095752
        Succeeded: 0
        Failed: 2
        Query Time: 0
        ================================
        
2016-11-03 21:37:04,138 | DEBUG    | gen_load_ratcheting  (326) | main | Sent 1 ATTRIB requests
2016-11-03 21:37:04,138 | INFO     | looper.py            (253) | shutdown | Looper shutting down now...
2016-11-03 21:37:04,143 | DEBUG    | motor.py             (34) | set_status | Claaaa10 changing status from started_hungry to stopping
2016-11-03 21:37:04,143 | INFO     | stacked.py           (82) | stop | stack Claaaa10 stopped
2016-11-03 21:37:04,143 | DEBUG    | motor.py             (34) | set_status | Claaaa10 changing status from stopping to stopped
2016-11-03 21:37:04,143 | INFO     | looper.py            (260) | shutdown | Looper shut down in 0.005 seconds.
2016-11-03 21:37:04,184 | DEBUG    | base_events.py       (410) | close | Close <_UnixSelectorEventLoop running=False closed=False debug=True>
